(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var m=ca(this);function q(a,b){if(b)a:{var c=m;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
q("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(k||"")+"_"+e++,k)}function c(k,g){this.g=k;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=m[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function r(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ka=fa;function la(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function ma(){this.m=!1;this.j=null;this.v=void 0;this.g=1;this.l=this.i=0;this.o=this.h=null}function na(a){if(a.m)throw new TypeError("Generator is already running");a.m=!0}f=ma.prototype;f.H=function(a){this.v=a};function oa(a,b){a.h={K:b,L:!0};a.g=a.i||a.l}f.return=function(a){this.h={return:a};this.g=this.l};f.Cd=function(a){this.h={C:a};this.g=this.l};
function pa(a,b,c){a.g=c;return{value:b}}f.pf=function(a,b){a=r(a);var c=a.next();la(c);if(c.done)this.v=c.value,this.g=b;else return this.j=a,pa(this,c.value,b)};f.C=function(a){this.g=a};f.Dd=function(){this.g=0};f.Rd=function(a){this.i=0;this.l=a||0};function qa(a,b){a.g=b;a.i=0}function ra(a){a.i=0;var b=a.h.K;a.h=null;return b}f.Fc=function(a,b,c){c?this.o[c]=this.h:this.o=[this.h];this.i=a||0;this.l=b||0};
f.Ed=function(a,b){b=this.o.splice(b||0)[0];(b=this.h=this.h||b)?b.L?this.g=this.i||this.l:void 0!=b.C&&this.l<b.C?(this.g=b.C,this.h=null):this.g=this.l:this.g=a};f.Ic=function(a){return new sa(a)};function sa(a){this.h=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}sa.prototype.i=function(){for(;0<this.g.length;){var a=this.g.pop();if(a in this.h)return a}return null};function ta(a){this.g=new ma;this.h=a}
function ua(a,b){na(a.g);var c=a.g.j;if(c)return va(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return wa(a)}function va(a,b,c,d){try{var e=b.call(a.g.j,c);la(e);if(!e.done)return a.g.m=!1,e;var k=e.value}catch(g){return a.g.j=null,oa(a.g,g),wa(a)}a.g.j=null;d.call(a.g,k);return wa(a)}
function wa(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.m=!1,{value:b.value,done:!1}}catch(c){a.g.v=void 0,oa(a.g,c)}a.g.m=!1;if(a.g.h){b=a.g.h;a.g.h=null;if(b.L)throw b.K;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function xa(a){this.next=function(b){na(a.g);a.g.j?b=va(a,a.g.j.next,b,a.g.H):(a.g.H(b),b=wa(a));return b};this.throw=function(b){na(a.g);a.g.j?b=va(a,a.g.j["throw"],b,a.g.H):(oa(a.g,b),b=wa(a));return b};this.return=function(b){return ua(a,b)};this[Symbol.iterator]=function(){return this}}function ya(a,b){b=new xa(new ta(b));ka&&a.prototype&&ka(b,a.prototype);return b}function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
q("WeakMap",function(a){function b(l){this.g=(h+=Math.random()+1).toString();if(l){l=r(l);for(var n;!(n=l.next()).done;)n=n.value,this.set(n[0],n[1])}}function c(){}function d(l){var n=typeof l;return"object"===n&&null!==l||"function"===n}function e(l){if(!t(l,g)){var n=new c;ba(l,g,{value:n})}}function k(l){var n=Object[l];n&&(Object[l]=function(p){if(p instanceof c)return p;Object.isExtensible(p)&&e(p);return n(p)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),n=Object.seal({}),
p=new a([[l,2],[n,3]]);if(2!=p.get(l)||3!=p.get(n))return!1;p.delete(l);p.set(n,4);return!p.has(l)&&4==p.get(n)}catch(G){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var h=0;b.prototype.set=function(l,n){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!t(l,g))throw Error("WeakMap key fail: "+l);l[g][this.g]=n;return this};b.prototype.get=function(l){return d(l)&&t(l,g)?l[g][this.g]:void 0};b.prototype.has=function(l){return d(l)&&t(l,
g)&&t(l[g],this.g)};b.prototype.delete=function(l){return d(l)&&t(l,g)&&t(l[g],this.g)?delete l[g][this.g]:!1};return b});
q("Map",function(a){function b(){var h={};return h.B=h.next=h.head=h}function c(h,l){var n=h.g;return da(function(){if(n){for(;n.head!=h.g;)n=n.B;for(;n.next!=n.head;)return n=n.next,{done:!1,value:l(n)};n=null}return{done:!0,value:void 0}})}function d(h,l){var n=l&&typeof l;"object"==n||"function"==n?k.has(l)?n=k.get(l):(n=""+ ++g,k.set(l,n)):n="p_"+l;var p=h.h[n];if(p&&t(h.h,n))for(h=0;h<p.length;h++){var G=p[h];if(l!==l&&G.key!==G.key||l===G.key)return{id:n,list:p,index:h,u:G}}return{id:n,list:p,
index:-1,u:void 0}}function e(h){this.h={};this.g=b();this.size=0;if(h){h=r(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),l=new a(r([[h,"s"]]));if("s"!=l.get(h)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var n=l.entries(),p=n.next();if(p.done||p.value[0]!=h||"s"!=p.value[1])return!1;p=n.next();return p.done||4!=p.value[0].x||
"t"!=p.value[1]||!n.next().done?!1:!0}catch(G){return!1}}())return a;var k=new WeakMap;e.prototype.set=function(h,l){h=0===h?0:h;var n=d(this,h);n.list||(n.list=this.h[n.id]=[]);n.u?n.u.value=l:(n.u={next:this.g,B:this.g.B,head:this.g,key:h,value:l},n.list.push(n.u),this.g.B.next=n.u,this.g.B=n.u,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.u&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.h[h.id],h.u.B.next=h.u.next,h.u.next.B=h.u.B,h.u.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.h={};this.g=this.g.B=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).u};e.prototype.get=function(h){return(h=d(this,h).u)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,l){for(var n=this.entries(),p;!(p=n.next()).done;)p=p.value,
h.call(l,p[1],p[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});function za(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}q("Array.prototype.entries",function(a){return a?a:function(){return za(this,function(b,c){return[b,c]})}});
function Aa(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}q("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=Aa(this,b,"endsWith");void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});
q("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.o=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(l){h.reject(l)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(null==this.g){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(g)};var e=m.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var l=
g[h];g[h]=null;try{l()}catch(n){this.j(n)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(n){return function(p){l||(l=!0,n.call(h,p))}}var h=this,l=!1;return{resolve:g(this.N),reject:g(this.l)}};b.prototype.N=function(g){if(g===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.P(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.M(g):this.m(g)}};
b.prototype.M=function(g){var h=void 0;try{h=g.then}catch(l){this.l(l);return}"function"==typeof h?this.R(h,g):this.m(g)};b.prototype.l=function(g){this.v(2,g)};b.prototype.m=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(0!=this.h)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;2===this.h&&this.O();this.D()};b.prototype.O=function(){var g=this;e(function(){if(g.V()){var h=m.console;"undefined"!==typeof h&&h.error(g.i)}},1)};b.prototype.V=
function(){if(this.o)return!1;var g=m.CustomEvent,h=m.Event,l=m.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=m.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return l(g)};b.prototype.D=function(){if(null!=this.g){for(var g=0;g<this.g.length;++g)k.h(this.g[g]);this.g=null}};var k=new c;b.prototype.P=
function(g){var h=this.j();g.F(h.resolve,h.reject)};b.prototype.R=function(g,h){var l=this.j();try{g.call(h,l.resolve,l.reject)}catch(n){l.reject(n)}};b.prototype.then=function(g,h){function l(u,J){return"function"==typeof u?function(U){try{n(u(U))}catch(Ta){p(Ta)}}:J}var n,p,G=new b(function(u,J){n=u;p=J});this.F(l(g,n),l(h,p));return G};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.F=function(g,h){function l(){switch(n.h){case 1:g(n.i);break;case 2:h(n.i);break;default:throw Error("Unexpected state: "+
n.h);}}var n=this;null==this.g?k.h(l):this.g.push(l);this.o=!0};b.resolve=d;b.reject=function(g){return new b(function(h,l){l(g)})};b.race=function(g){return new b(function(h,l){for(var n=r(g),p=n.next();!p.done;p=n.next())d(p.value).F(h,l)})};b.all=function(g){var h=r(g),l=h.next();return l.done?d([]):new b(function(n,p){function G(U){return function(Ta){u[U]=Ta;J--;0==J&&n(u)}}var u=[],J=0;do u.push(void 0),J++,d(l.value).F(G(u.length-1),p),l=h.next();while(!l.done)})};return b});
q("Array.prototype.values",function(a){return a?a:function(){return za(this,function(b,c){return c})}});q("Array.prototype.keys",function(a){return a?a:function(){return za(this,function(b){return b})}});
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],k="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof k){b=k.call(b);for(var g=0;!(k=b.next()).done;)e.push(c.call(d,k.value,g++))}else for(k=b.length,g=0;g<k;g++)e.push(c.call(d,b[g],g));return e}});q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var k=d[c];if(k===b||Object.is(k,b))return!0}return!1}});q("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==Aa(this,b,"includes").indexOf(b,c||0)}});var v=this||self;
function Ba(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}function Ca(a,b){a=a.split(".");var c=v;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function Da(a){return a};var w=new Map([]);w.set("devsite-a11y-announce",{src:"/developers/js/devsite_devsite_a11y_announce_module.js"});w.set("devsite-analytics",{src:"/developers/js/devsite_devsite_analytics_module.js"});w.set("devsite-analytics-scope",{src:"/developers/js/devsite_devsite_analytics_scope_module.js"});w.set("devsite-anselm",{src:"/developers/js/devsite_devsite_anselm_module.js"});w.set("devsite-api-getstarted",{src:"/developers/js/devsite_devsite_api_getstarted_module.js"});w.set("devsite-apix",{src:"/developers/js/devsite_devsite_apix_module.js"});
w.set("devsite-apix-index",{src:"/developers/js/devsite_devsite_apix_index_module.js"});w.set("devsite-apix-snippets",{src:"/developers/js/devsite_devsite_apix_snippets_module.js"});w.set("devsite-badger",{src:"/developers/js/devsite_devsite_badger_module.js"});w.set("devsite-badge-awarded",{src:"/developers/js/devsite_devsite_badge_awarded_module.js"});w.set("devsite-badge-awarder",{src:"/developers/js/devsite_devsite_badge_awarder_module.js"});w.set("devsite-badge-redeemer",{src:"/developers/js/devsite_devsite_badge_redeemer_module.js"});
w.set("devsite-book-nav",{src:"/developers/js/devsite_devsite_book_nav_module.js"});w.set("devsite-bookmark",{src:"/developers/js/devsite_devsite_bookmark_module.js"});w.set("devsite-chart",{src:"/developers/js/devsite_devsite_chart_module.js"});w.set("devsite-catalog",{src:"/developers/js/devsite_devsite_catalog_module.js"});w.set("devsite-code",{src:"/developers/js/devsite_devsite_code_module.js"});w.set("devsite-content",{src:"/developers/js/devsite_devsite_content_module.js"});
w.set("devsite-codelab-catalog",{src:"/developers/js/devsite_devsite_codelab_catalog_module.js"});w.set("devsite-product-catalog",{src:"/developers/js/devsite_devsite_product_catalog_module.js"});w.set("devsite-credentials-dialog",{src:"/developers/js/devsite_devsite_credentials_dialog_module.js"});w.set("devsite-cse",{src:"/developers/js/devsite_devsite_cse_module.js"});w.set("devsite-panel",{src:"/developers/js/devsite_devsite_panel_module.js"});w.set("devsite-device",{src:"/developers/js/devsite_devsite_device_module.js"});
w.set("devsite-devprofile",{src:"/developers/js/devsite_devsite_devprofile_module.js"});w.set("devsite-dialog",{src:"/developers/js/devsite_devsite_dialog_module.js"});w.set("devsite-dynamic-content",{src:"/developers/js/devsite_devsite_dynamic_content_module.js"});w.set("devsite-expandable",{src:"/developers/js/devsite_devsite_expandable_module.js"});w.set("devsite-expandable-nav",{src:"/developers/js/devsite_devsite_expandable_nav_module.js"});w.set("devsite-extradory",{src:"/developers/js/devsite_devsite_extradory_module.js"});
w.set("devsite-feedback",{src:"/developers/js/devsite_devsite_feedback_module.js"});w.set("devsite-filter",{src:"/developers/js/devsite_devsite_filter_module.js"});w.set("devsite-footer-linkboxes",{src:"/developers/js/devsite_devsite_footer_linkboxes_module.js"});w.set("devsite-footer-promos",{src:"/developers/js/devsite_devsite_footer_promos_module.js"});w.set("devsite-footer-utility",{src:"/developers/js/devsite_devsite_footer_utility_module.js"});w.set("devsite-google-survey",{src:"/developers/js/devsite_devsite_google_survey_module.js"});
w.set("devsite-googler-buttons",{src:"/developers/js/devsite_devsite_googler_buttons_module.js"});w.set("devsite-hats-survey",{src:"/developers/js/devsite_devsite_hats_survey_module.js"});w.set("devsite-header",{src:"/developers/js/devsite_devsite_header_module.js"});w.set("devsite-heading-link",{src:"/developers/js/devsite_devsite_heading_link_module.js"});w.set("devsite-iframe",{src:"/developers/js/devsite_devsite_iframe_module.js"});w.set("devsite-info-popout",{src:"/developers/js/devsite_devsite_info_popout_module.js"});
w.set("devsite-jump-to",{src:"/developers/js/devsite_devsite_jump_to_module.js"});w.set("devsite-jsfiddle-button",{src:"/developers/js/devsite_devsite_jsfiddle_button_module.js"});w.set("devsite-language-selector",{src:"/developers/js/devsite_devsite_language_selector_module.js"});w.set("devsite-lightbox",{src:"/developers/js/devsite_devsite_lightbox_module.js"});w.set("devsite-mathjax",{src:"/developers/js/devsite_devsite_mathjax_module.js"});w.set("devsite-mdc",{src:"/developers/js/devsite_devsite_mdc_module.js"});
w.set("devsite-multiple-choice",{src:"/developers/js/devsite_devsite_multiple_choice_module.js"});w.set("devsite-nav-buttons",{src:"/developers/js/devsite_devsite_nav_buttons_module.js"});w.set("devsite-playlist",{src:"/developers/js/devsite_devsite_playlist_module.js"});w.set("devsite-playlist-earnable-badges",{src:"/developers/js/devsite_devsite_playlist_earnable_badges_module.js"});w.set("devsite-playlist-summary",{src:"/developers/js/devsite_devsite_playlist_summary_module.js"});
w.set("devsite-pagination",{src:"/developers/js/devsite_devsite_pagination_module.js"});w.set("devsite-profile-card",{src:"/developers/js/devsite_devsite_profile_card_module.js"});w.set("devsite-progress",{src:"/developers/js/devsite_devsite_progress_module.js"});w.set("devsite-quiz",{src:"/developers/js/devsite_devsite_quiz_module.js"});w.set("devsite-recommendations",{src:"/developers/js/devsite_devsite_recommendations_module.js"});w.set("devsite-recommendations-dropdown",{src:"/developers/js/devsite_devsite_recommendations_dropdown_module.js"});
w.set("devsite-recommendations-sidebar",{src:"/developers/js/devsite_devsite_recommendations_sidebar_module.js"});w.set("devsite-reference-results",{src:"/developers/js/devsite_devsite_reference_results_module.js"});w.set("devsite-search",{src:"/developers/js/devsite_devsite_search_module.js"});w.set("devsite-select",{src:"/developers/js/devsite_devsite_select_module.js"});w.set("devsite-selector",{src:"/developers/js/devsite_devsite_selector_module.js"});w.set("devsite-shell",{src:"/developers/js/devsite_devsite_shell_module.js"});
w.set("devsite-shell-activate-button",{src:"/developers/js/devsite_devsite_shell_activate_button_module.js"});w.set("devsite-sitemask",{src:"/developers/js/devsite_devsite_sitemask_module.js"});w.set("devsite-snackbar",{src:"/developers/js/devsite_devsite_snackbar_module.js"});w.set("devsite-sort",{src:"/developers/js/devsite_devsite_sort_module.js"});w.set("devsite-spinner",{src:"/developers/js/devsite_devsite_spinner_module.js"});w.set("devsite-support-form",{src:"/developers/js/devsite_devsite_support_form_module.js"});
w.set("devsite-tabs",{src:"/developers/js/devsite_devsite_tabs_module.js"});w.set("devsite-theme-selector",{src:"/developers/js/devsite_devsite_theme_selector_module.js"});w.set("devsite-thumb-rating",{src:"/developers/js/devsite_devsite_thumb_rating_module.js"});w.set("devsite-toc",{src:"/developers/js/devsite_devsite_toc_module.js"});w.set("devsite-topic",{src:"/developers/js/devsite_devsite_topic_module.js"});w.set("devsite-tooltip",{src:"/developers/js/devsite_devsite_tooltip_module.js"});
w.set("devsite-tracking-question",{src:"/developers/js/devsite_devsite_tracking_question_module.js"});w.set("devsite-user",{src:"/developers/js/devsite_devsite_user_module.js"});w.set("devsite-var",{src:"/developers/js/devsite_devsite_var_module.js"});w.set("devsite-version-selector",{src:"/developers/js/devsite_devsite_version_selector_module.js"});w.set("devsite-visibility-analytics",{src:"/developers/js/devsite_devsite_visibility_analytics_module.js"});w.set("devsite-vplus",{src:"/developers/js/devsite_devsite_vplus_module.js"});
w.set("devsite-wall-acknowledgement",{src:"/developers/js/devsite_devsite_wall_acknowledgement_module.js"});w.set("devsite-youtube",{src:"/developers/js/devsite_devsite_youtube_module.js"});w.set("google-codelab",{src:"/developers/js/devsite_google_codelab_module.js"});w.set("google-codelab-about",{src:"/developers/js/devsite_google_codelab_about_module.js"});w.set("google-codelab-analytics",{src:"/developers/js/devsite_google_codelab_analytics_module.js"});w.set("google-codelab-step",{src:"/developers/js/devsite_google_codelab_step_module.js"});
w.set("google-codelab-survey",{src:"/developers/js/devsite_google_codelab_survey_module.js"});w.set("devsite-avatar",{src:"/developers/js/devsite_devsite_avatar_module.js"});w.set("devsite-activity-list",{src:"/developers/js/devsite_devsite_activity_list_module.js"});w.set("devsite-badge",{src:"/developers/js/devsite_devsite_badge_module.js"});w.set("devsite-mwc",{src:"/developers/js/devsite_devsite_mwc_module.js"});w.set("devsite-profile",{src:"/developers/js/devsite_devsite_profile_module.js"});
w.set("devsite-profile-dashboard",{src:"/developers/js/devsite_devsite_profile_dashboard_module.js"});w.set("devsite-profile-interests",{src:"/developers/js/devsite_devsite_profile_interests_module.js"});w.set("devsite-profile-recommendations",{src:"/developers/js/devsite_devsite_profile_recommendations_module.js"});w.set("devsite-profile-wizard",{src:"/developers/js/devsite_devsite_profile_wizard_module.js"});w.set("devsite-profile-router",{src:"/developers/js/devsite_devsite_profile_router_module.js"});
w.set("devsite-profiles-splash",{src:"/developers/js/devsite_devsite_profiles_splash_module.js"});Ca("DevsiteAppAuthorizedElements",w);Ca("DevsiteAppTenantCustomized",!0);var Ea={sc:0,rc:1,Xb:6,Vb:8,bc:12,cc:14,dc:17,hc:18,jc:21,lc:25,za:37,mc:38,Ka:40,lb:45,la:47,X:50,fa:52,ca:62,Xa:63,Fb:66,wb:70,Y:73,qb:74,na:75,Cb:76,Ta:77,Va:80,da:81,ib:82,Ra:83,vb:85,sa:87,Ma:89,yb:90,Na:91,Ua:92,ja:93,pc:94,Qa:95,ia:96,Gb:97,Z:98,aa:99,kc:100,Ja:101,Sa:102,Bb:103,oc:104,ua:105,ka:106,Ha:107,xa:108,ub:109,ta:110,Ga:111,nc:112,Db:113,ya:114,ha:115,Ba:116,jb:117,hb:118,Oa:119,xb:120,$b:121,Eb:122,ec:123,Wb:124,eb:125,rb:126,Ia:127,ac:128,nb:129,ob:130,Ea:131,bb:132,$:133,Ya:134,
La:135,kb:136,ba:137,qc:138,sb:139,Yb:140,Ub:141,mb:142,gb:143,tb:144,ga:145,pb:146,Za:147,fb:148,zb:149,wa:150,ra:151,$a:152,Fa:153,Da:154,ma:155,ic:156,fc:157,Wa:158,Ca:159,ea:160,oa:161,va:162,Zb:163,Ab:164,Aa:165,pa:166,Hb:167,qa:168,cb:169,ab:170,Pa:171};var Fa,Ga="undefined"!==typeof TextEncoder;
function Ha(a){if(Ga)a=(Fa||(Fa=new TextEncoder)).encode(a);else{var b=void 0;b=void 0===b?!1:b;for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var k=a.charCodeAt(e);if(128>k)d[c++]=k;else{if(2048>k)d[c++]=k>>6|192;else{if(55296<=k&&57343>=k){if(56319>=k&&e<a.length){var g=a.charCodeAt(++e);if(56320<=g&&57343>=g){k=1024*(k-55296)+g-56320+65536;d[c++]=k>>18|240;d[c++]=k>>12&63|128;d[c++]=k>>6&63|128;d[c++]=k&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");k=65533}d[c++]=
k>>12|224;d[c++]=k>>6&63|128}d[c++]=k&63|128}}a=d.subarray(0,c)}return a};var Ia=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var Ja={},Ka=null;function La(a,b){void 0===b&&(b=0);Ma();b=Ja[b];for(var c=Array(Math.floor(a.length/3)),d=b[64]||"",e=0,k=0;e<a.length-2;e+=3){var g=a[e],h=a[e+1],l=a[e+2],n=b[g>>2];g=b[(g&3)<<4|h>>4];h=b[(h&15)<<2|l>>6];l=b[l&63];c[k++]=n+g+h+l}n=0;l=d;switch(a.length-e){case 2:n=a[e+1],l=b[(n&15)<<2]||d;case 1:a=a[e],c[k]=b[a>>2]+b[(a&3)<<4|n>>4]+l+d}return c.join("")}
function Na(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):-1!="=.".indexOf(a[b-1])&&(c=-1!="=.".indexOf(a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;Oa(a,function(k){d[e++]=k});return d.subarray(0,e)}
function Oa(a,b){function c(l){for(;d<a.length;){var n=a.charAt(d++),p=Ka[n];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(n))throw Error("Unknown base64 encoding at char: "+n);}return l}Ma();for(var d=0;;){var e=c(-1),k=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;b(e<<2|k>>4);64!=g&&(b(k<<4&240|g>>2),64!=h&&b(g<<6&192|h))}}
function Ma(){if(!Ka){Ka={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));Ja[c]=d;for(var e=0;e<d.length;e++){var k=d[e];void 0===Ka[k]&&(Ka[k]=e)}}}};var Pa="function"===typeof Uint8Array.prototype.slice,Qa,x=0,y=0;function Ra(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;x=b;y=a}function z(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));x=c;y=a}function Sa(a){var b=0>a;a=2*Math.abs(a);Ra(a);a=x;var c=y;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);x=a;y=c}
function Ua(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?x=y=0:(y=0,x=2147483648);else if(isNaN(a))y=0,x=2147483647;else if(3.4028234663852886E38<a)y=0,x=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),y=0,x=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a);16777216<=a&&++c;y=0;x=(b<<31|c+127<<23|a&8388607)>>>0}}
function Va(a){var b=r(a);a=b.next().value;var c=b.next().value,d=b.next().value,e=b.next().value,k=b.next().value,g=b.next().value,h=b.next().value;b=b.next().value;x=a+(c<<8)+(d<<16)+(e<<24)>>>0;y=k+(g<<8)+(h<<16)+(b<<24)>>>0}function Wa(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function Xa(a){function b(g,h){for(var l=0;8>l&&(1!==g||0<h);l++)h=g*e[l]+h,e[l]=h&255,h>>>=8}function c(){for(var g=0;8>g;g++)e[g]=~e[g]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],k=0;k<a.length;k++)b(10,a.charCodeAt(k)-48);d&&(c(),b(1,1));return e}
function Ya(a){return a.constructor===Uint8Array?a:a.constructor===ArrayBuffer?new Uint8Array(a):a.constructor===Array?new Uint8Array(a):a.constructor===String?Na(a):a instanceof Uint8Array?new Uint8Array(a.buffer,a.byteOffset,a.byteLength):new Uint8Array(0)};function A(a,b){this.g=a;this.h=b}function Za(a){return new A((a.g>>>1|(a.h&1)<<31)>>>0,a.h>>>1>>>0)}function $a(a){return new A(a.g<<1>>>0,(a.h<<1|a.g>>>31)>>>0)}f=A.prototype;f.Fd=function(){return!!(this.g&1)};f.add=function(a){return new A((this.g+a.g&4294967295)>>>0>>>0,((this.h+a.h&4294967295)>>>0)+(4294967296<=this.g+a.g?1:0)>>>0)};f.sub=function(a){return new A((this.g-a.g&4294967295)>>>0>>>0,((this.h-a.h&4294967295)>>>0)-(0>this.g-a.g?1:0)>>>0)};
function ab(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new A(a>>>0,b>>>0)}f.toString=function(){for(var a="",b=this;0!=b.g||0!=b.h;){var c=new A(0,0);b=new A(b.g,b.h);for(var d=new A(10,0),e=new A(1,0);!(d.h&2147483648);)d=$a(d),e=$a(e);for(;0!=e.g||0!=e.h;)0>=(d.h<b.h||d.h==b.h&&d.g<b.g?-1:d.h==b.h&&d.g==b.g?0:1)&&(c=c.add(e),b=b.sub(d)),d=Za(d),e=Za(e);c=[c,b];b=c[0];a=c[1].g+a}""==a&&(a="0");return a};
function bb(a){for(var b=new A(0,0),c=new A(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.g=parseInt(a[d],10);var e=ab(b.g);b=ab(b.h);b.h=b.g;b.g=0;b=e.add(b).add(c)}return b}f.Ib=function(){return new A(this.g,this.h)};function B(a,b){this.g=a;this.h=b}B.prototype.add=function(a){return new B((this.g+a.g&4294967295)>>>0>>>0,((this.h+a.h&4294967295)>>>0)+(4294967296<=this.g+a.g?1:0)>>>0)};
B.prototype.sub=function(a){return new B((this.g-a.g&4294967295)>>>0>>>0,((this.h-a.h&4294967295)>>>0)-(0>this.g-a.g?1:0)>>>0)};B.prototype.i=function(){return new B(this.g,this.h)};B.prototype.toString=function(){var a=0!=(this.h&2147483648),b=new A(this.g,this.h);a&&(b=(new A(0,0)).sub(b));return(a?"-":"")+b.toString()};function cb(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=bb(a);if(null===a)return null;b&&(a=(new A(0,0)).sub(a));return new B(a.g,a.h)};function db(){this.h=new Uint8Array(64);this.g=0}function eb(a,b){if(!(a.g+b<a.h.length)){var c=a.h;a.h=new Uint8Array(Math.ceil(b+2*a.h.length));a.h.set(c)}}function C(a,b){eb(a,1);a.h[a.g++]=b}f=db.prototype;f.Jb=function(a){eb(this,a.length);this.h.set(a,this.g);this.g+=a.length};f.length=function(){return this.g};f.end=function(){var a=this.h,b=this.g;this.g=0;return 0===b?Qa||(Qa=new Uint8Array(0)):Pa?a.slice(0,b):new Uint8Array(a.subarray(0,b))};
function D(a,b,c){for(;0<c||127<b;)C(a,b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;C(a,b)}function E(a,b,c){F(a,b);F(a,c)}function fb(a,b,c){Wa(b,c,function(d,e){D(a,d>>>0,e>>>0)})}function H(a,b){for(;127<b;)C(a,b&127|128),b>>>=7;C(a,b)}function gb(a,b){if(0<=b)H(a,b);else{for(var c=0;9>c;c++)C(a,b&127|128),b>>=7;C(a,1)}}function hb(a,b){H(a,(b<<1^b>>31)>>>0)}function ib(a,b){Va(Xa(b));Wa(x,y,function(c,d){D(a,c>>>0,d>>>0)})}f.nf=function(a){C(this,a>>>0&255)};
f.mf=function(a){C(this,a>>>0&255);C(this,a>>>8&255)};function F(a,b){C(a,b>>>0&255);C(a,b>>>8&255);C(a,b>>>16&255);C(a,b>>>24&255)}function jb(a,b){Ra(b);F(a,x);F(a,y)}f.ne=function(a){C(this,a>>>0&255)};f.me=function(a){C(this,a>>>0&255);C(this,a>>>8&255)};function kb(a,b){C(a,b>>>0&255);C(a,b>>>8&255);C(a,b>>>16&255);C(a,b>>>24&255)}
function lb(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)y=0<1/c?0:2147483648,x=0;else if(isNaN(c))y=2147483647,x=4294967295;else if(1.7976931348623157E308<c)y=(b<<31|2146435072)>>>0,x=0;else if(2.2250738585072014E-308>c){var d=c/Math.pow(2,-1074);y=(b<<31|d/4294967296)>>>0;x=d>>>0}else{var e=c;d=0;if(2<=e)for(;2<=e&&1023>d;)d++,e/=2;else for(;1>e&&-1022<d;)e*=2,d--;c*=Math.pow(2,-d);y=(b<<31|d+1023<<20|1048576*c&1048575)>>>0;x=4503599627370496*c>>>0}F(a,x);F(a,y)};function mb(){this.i=[];this.h=0;this.g=new db}function nb(a,b){0!==b.length&&(a.i.push(b),a.h+=b.length)}function ob(a){nb(a,a.g.end())}function I(a,b){K(a,b,2);ob(a);return{U:a.h,S:a.i.length-1}}function L(a,b){ob(a);H(a.g,a.h+a.g.length()-b.U);var c=a.g.end();a.h+=c.length;a.i.splice(1+b.S,0,c)}f=mb.prototype;f.Id=function(a,b,c){null!=a&&null!=b&&null!=c&&(a=a.subarray(b,c),ob(this),nb(this,a))};
function pb(a){var b=a.h+a.g.length();if(0===b)return new Uint8Array(0);b=new Uint8Array(b);for(var c=a.i,d=c.length,e=0,k=0;k<d;k++){var g=c[k];0!==g.length&&(b.set(g,e),e+=g.length)}c=a.g;d=c.g;0!==d&&(b.set(c.h.subarray(0,d),e),c.g=0);a.i=[b];return b}f.Uc=function(a){return La(pb(this),a)};function K(a,b,c){H(a.g,8*b+c)}
f.ke=function(a,b,c){switch(a){case 1:null!=c&&(K(this,b,1),lb(this.g,c));break;case 2:null!=c&&(K(this,b,5),a=this.g,Ua(c),F(a,x));break;case 3:null!=c&&null!=c&&(K(this,b,0),a=this.g,z(c),D(a,x,y));break;case 4:null!=c&&null!=c&&(K(this,b,0),a=this.g,z(c),D(a,x,y));break;case 5:null!=c&&null!=c&&(K(this,b,0),gb(this.g,c));break;case 6:null!=c&&(K(this,b,1),jb(this.g,c));break;case 7:null!=c&&(K(this,b,5),F(this.g,c));break;case 8:qb(this,b,c);break;case 9:null!=c&&rb(this,b,Ha(c));break;case 12:null!=
c&&rb(this,b,Ya(c));break;case 13:null!=c&&null!=c&&(K(this,b,0),H(this.g,c));break;case 14:sb(this,b,c);break;case 15:null!=c&&(K(this,b,5),kb(this.g,c));break;case 16:null!=c&&(K(this,b,1),a=this.g,z(c),E(a,x,y));break;case 17:null!=c&&null!=c&&(K(this,b,0),hb(this.g,c));break;case 18:null!=c&&null!=c&&(K(this,b,0),a=this.g,Sa(c),D(a,x,y))}};f.lf=function(a,b){null!=b&&null!=b&&(K(this,a,0),ib(this.g,b))};function qb(a,b,c){null!=c&&(K(a,b,0),C(a.g,c?1:0))}
function sb(a,b,c){null!=c&&(c=parseInt(c,10),K(a,b,0),gb(a.g,c))}function rb(a,b,c){K(a,b,2);H(a.g,c.length);ob(a);nb(a,c)}f.oe=function(a,b,c){null!=b&&(a=I(this,a),c(b,this),L(this,a))};f.pe=function(a,b,c){null!=b&&(K(this,1,3),K(this,2,0),gb(this.g,a),a=I(this,3),c(b,this),L(this,a),K(this,1,4))};f.le=function(a,b,c){null!=b&&(K(this,a,3),c(b,this),K(this,a,4))};f.Ve=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),gb(this.g,d))}};
f.We=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,0);var e=this.g;z(d);D(e,x,y)}}};f.ef=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);K(this,a,1);E(this.g,k,g)}};f.ff=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);K(this,a,0);D(this.g,k,g)}};f.gf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);K(this,a,0);fb(this.g,k>>>0,g>>>0)}};
f.Xe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=cb(e),K(this,d,0),D(this.g,e.g,e.h))}};f.hf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),H(this.g,d))}};f.jf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,0);var e=this.g;z(d);D(e,x,y)}}};f.kf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=bb(e),K(this,d,0),D(this.g,e.g,e.h))}};
f.bf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),hb(this.g,d))}};f.cf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,0);var e=this.g;Sa(d);D(e,x,y)}}};f.df=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),ib(this.g,d))}};f.Qe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,5),F(this.g,d))}};
f.Re=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,1),jb(this.g,d))}};f.Se=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=bb(e),K(this,d,1),E(this.g,e.g,e.h))}};f.Ze=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,5),kb(this.g,d))}};f.$e=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,1);var e=this.g;z(d);E(e,x,y)}}};
f.af=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=cb(e),K(this,d,1),E(this.g,e.g,e.h))}};f.Te=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,5);var e=this.g;Ua(d);F(e,x)}}};f.Oe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,1),lb(this.g,d))}};f.Me=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)qb(this,a,b[c])};f.Pe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)sb(this,a,b[c])};
function tb(a,b,c){if(null!=c)for(var d=0;d<c.length;d++){var e=c[d];null!=e&&rb(a,b,Ha(e))}}f.Ne=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&rb(this,a,Ya(d))}};f.Ye=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++){var e=I(this,a);c(b[d],this);L(this,e)}};f.Ue=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)K(this,a,3),c(b[d],this),K(this,a,4)};f.we=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++)gb(this.g,b[c]);L(this,a)}};
f.xe=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++)gb(this.g,parseInt(b[c],10));L(this,a)}};f.ye=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++){var d=this.g;z(b[c]);D(d,x,y)}L(this,a)}};f.Ge=function(a,b,c,d){if(null!=b){a=I(this,a);for(var e=0;e<b.length;e++)E(this.g,c(b[e]),d(b[e]));L(this,a)}};f.He=function(a,b,c,d){if(null!=b){a=I(this,a);for(var e=0;e<b.length;e++)D(this.g,c(b[e]),d(b[e]));L(this,a)}};
f.Ie=function(a,b,c,d){if(null!=b){a=I(this,a);for(var e=this.g,k=0;k<b.length;k++)fb(e,c(b[k]),d(b[k]));L(this,a)}};f.ze=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++){var d=cb(b[c]);D(this.g,d.g,d.h)}L(this,a)}};f.Je=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++)H(this.g,b[c]);L(this,a)}};f.Ke=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++){var d=this.g;z(b[c]);D(d,x,y)}L(this,a)}};
f.Le=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++){var d=bb(b[c]);D(this.g,d.g,d.h)}L(this,a)}};f.De=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++)hb(this.g,b[c]);L(this,a)}};f.Ee=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++){var d=this.g;Sa(b[c]);D(d,x,y)}L(this,a)}};f.Fe=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++)ib(this.g,b[c]);L(this,a)}};
f.se=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,4*b.length),a=0;a<b.length;a++)F(this.g,b[a])};f.te=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++)jb(this.g,b[a])};f.ue=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++){var c=bb(b[a]);E(this.g,c.g,c.h)}};f.Ae=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,4*b.length),a=0;a<b.length;a++)kb(this.g,b[a])};
f.Be=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++){var c=this.g;z(b[a]);E(c,x,y)}};f.Ce=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++){var c=this.g;Va(Xa(b[a]));E(c,x,y)}};f.ve=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,4*b.length),a=0;a<b.length;a++){var c=this.g;Ua(b[a]);F(c,x)}};f.re=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++)lb(this.g,b[a])};
f.qe=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,b.length),a=0;a<b.length;a++)C(this.g,b[a]?1:0)};var ub="function"===typeof Uint8Array;function vb(a){return null!==a&&"object"==typeof a&&!Array.isArray(a)&&!wb(a)}function xb(a,b){if(null!=a)return Array.isArray(a)||vb(a)?yb(a,b):b(a)}function yb(a,b){if(Array.isArray(a)){for(var c=Array(a.length),d=0;d<a.length;d++)c[d]=xb(a[d],b);Array.isArray(a)&&a.T&&M(c);return c}c={};for(d in a)c[d]=xb(a[d],b);return c}function zb(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":return wb(a)?La(a):a;default:return a}}
function Ab(a){return wb(a)?new Uint8Array(a):a}var Bb={T:{value:!0,configurable:!0}};function M(a){Array.isArray(a)&&!Object.isFrozen(a)&&Object.defineProperties(a,Bb);return a}var Cb;function wb(a){return ub&&null!=a&&a instanceof Uint8Array};function Db(a,b){this.i=a;this.j=b;this.g={};this.h=!0;this.l=null;if(0<this.i.length){for(a=0;a<this.i.length;a++){b=this.i[a];var c=b[0];this.g[c.toString()]=new Eb(c,b[1])}this.h=!0}}f=Db.prototype;f.isFrozen=function(){return!1};f.toJSON=function(){var a=this.s();return Cb?a:yb(a,zb)};f.Lb=function(){return this.toJSON()};
f.s=function(){if(this.h){if(this.j){var a=this.g,b;for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var c=a[b].g;c&&c.s()}}}else{this.i.length=0;a=Fb(this);a.sort();for(b=0;b<a.length;b++){c=this.g[a[b]];var d=c.g;d&&d.s();this.i.push([c.key,c.value])}this.h=!0}return this.i};f.Qc=function(){return Fb(this).length};f.Kb=function(){this.g={};this.h=!1};f.Dc=function(a){a=a.toString();var b=this.g.hasOwnProperty(a);delete this.g[a];this.h=!1;return b};
f.Oc=function(){var a=[],b=Fb(this);b.sort();for(var c=0;c<b.length;c++){var d=this.g[b[c]];a.push([d.key,d.value])}return a};f.entries=function(){var a=[],b=Fb(this);b.sort();for(var c=0;c<b.length;c++){var d=this.g[b[c]];a.push([d.key,Gb(this,d)])}return new Hb(a)};f.keys=function(){var a=[],b=Fb(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.g[b[c]].key);return new Hb(a)};f.values=function(){var a=[],b=Fb(this);b.sort();for(var c=0;c<b.length;c++)a.push(Gb(this,this.g[b[c]]));return new Hb(a)};
f.forEach=function(a,b){var c=Fb(this);c.sort();for(var d=0;d<c.length;d++){var e=this.g[c[d]];a.call(b,Gb(this,e),e.key,this)}};f.set=function(a,b){var c=new Eb(a);this.j?(c.g=b,c.value=b.s()):c.value=b;this.g[a.toString()]=c;this.h=!1;return this};f.ae=function(a,b){this.g[a.toString()]=new Eb(a,b);this.h=!1};function Gb(a,b){return a.j?(b.g||(b.g=new a.j(b.value),a.isFrozen()&&null(b.g)),b.g):b.value}f.get=function(a){if(a=this.g[a.toString()])return Gb(this,a)};
f.has=function(a){return a.toString()in this.g};function Fb(a){a=a.g;var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}Db.prototype[Symbol.iterator]=function(){return this.entries()};function Eb(a,b){this.key=a;this.value=b;this.g=void 0}function Hb(a){this.h=0;this.g=a}Hb.prototype.next=function(){return this.h<this.g.length?{done:!1,value:this.g[this.h++]}:{done:!0,value:void 0}};Hb.prototype[Symbol.iterator]=function(){return this};var Ib;function Jb(a,b){Ib=b;a=new a(b);Ib=null;return a};function N(a,b,c){var d=Ib;Ib=null;a||(a=d);d=this.constructor.Jd;a||(a=d?[d]:[]);this.l=d?0:-1;this.i=this.g=null;this.h=a;a:{d=this.h.length;a=d-1;if(d&&(d=this.h[a],vb(d))){this.m=a-this.l;this.j=d;break a}void 0!==b&&-1<b?(this.m=Math.max(b,a+1-this.l),this.j=null):this.m=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.m?(a+=this.l,(d=this.h[a])?M(d):this.h[a]=O):(Kb(this),(d=this.j[a])?M(d):this.j[a]=O)}var O=Object.freeze(M([]));
function Kb(a){var b=a.m+a.l;a.h[b]||(a.j=a.h[b]={})}function P(a,b,c){return-1===b?null:(void 0===c?0:c)||b>=a.m?a.j?a.j[b]:void 0:a.h[b+a.l]}f=N.prototype;f.qd=function(a){return null!=P(this,a)};f.rd=function(a,b){return Lb(this,b)===a};function Q(a,b){var c=void 0===c?!1:c;var d=P(a,b,c);null==d&&(d=O);d===O&&(d=M([]),R(a,b,d,c));return d}function Mb(a,b){a=P(a,b);return null==a?a:+a}function Nb(a,b){a=P(a,b);return null==a?a:!!a}
f.pd=function(a){var b=Q(this,a);this.i||(this.i={});if(!this.i[a]){for(var c=0;c<b.length;c++)b[c]=+b[c];this.i[a]=!0}return b};f.od=function(a){var b=Q(this,a);this.i||(this.i={});if(!this.i[a]){for(var c=0;c<b.length;c++)b[c]=!!b[c];this.i[a]=!0}return b};function Ob(a,b,c){a=P(a,b);return null==a?c:a}function Pb(a,b,c){a=Nb(a,b);return null==a?void 0===c?!1:c:a}function Qb(a,b,c){a.g||(a.g={});if(b in a.g)return a.g[b];var d=P(a,b);d||(d=M([]),R(a,b,d));c=new Db(d,c);return a.g[b]=c}
function R(a,b,c,d){(void 0===d?0:d)||b>=a.m?(Kb(a),a.j[b]=c):a.h[b+a.l]=c;return a}function Rb(a,b,c,d){d=void 0===d?!1:d;return R(a,b,M(c||[]),d)}f.cd=function(a){return Sb(this,a,void 0)};f.bd=function(a){return Tb(this,a,void 0)};function S(a,b,c,d){c!==d?R(a,b,c):R(a,b,void 0);return a}function Ub(a,b,c,d){b=Q(a,b);void 0!=d?b.splice(d,0,c):b.push(c);return a}function Lb(a,b){for(var c=0,d=0;d<b.length;d++){var e=b[d];null!=P(a,e)&&(0!==c&&R(a,c,void 0),c=e)}return c}
function Vb(a,b,c,d,e){if(-1===c)return null;a.g||(a.g={});!a.g[c]&&(e=P(a,c,void 0===e?!1:e),d||e)&&(a.g[c]=new b(e));return a.g[c]}function Wb(a,b,c){a.g||(a.g={});var d=a.g[c];if(!d){var e=Q(a,c);d=[];for(var k=0;k<e.length;k++)d[k]=new b(e[k]);a.g[c]=d}return d}function Sb(a,b,c,d){d=void 0===d?!1:d;a.g||(a.g={});var e=c?c.s():c;a.g[b]=c;return R(a,b,e,d)}
f.sd=function(a,b,c){this.g||(this.g={});var d=c?c.s():c;this.g[a]=c;(b=Lb(this,b))&&b!==a&&null!=d&&(this.g&&b in this.g&&(this.g[b]=void 0),R(this,b,void 0));return R(this,a,d)};function Tb(a,b,c,d){d=void 0===d?!1:d;if(c){var e=M([]);for(var k=0;k<c.length;k++)e[k]=c[k].s();a.g||(a.g={});a.g[b]=c}else a.g&&(a.g[b]=void 0),e=O;return R(a,b,e,d)}f.ad=function(a,b,c,d){var e=Wb(this,c,a);b=b?b:new c;a=Q(this,a);void 0!=d?(e.splice(d,0,b),a.splice(d,0,b.s())):(e.push(b),a.push(b.s()));return this};
f.Ob=function(){return this.toJSON()};f.ie=function(){return this.toJSON()};f.toJSON=function(){var a=this.s();return Cb?a:yb(a,zb)};f.je=function(){return yb(this.s(),Ab)};f.s=function(){if(this.g)for(var a in this.g){var b=this.g[a];if(Array.isArray(b))for(var c=0;c<b.length;c++)b[c]&&b[c].s();else b&&b.s()}return this.h};function Xb(a,b){return zb(b)}function Yb(){var a=Zb.g;Cb=!0;try{return JSON.stringify(a.toJSON(),Xb)}finally{Cb=!1}}f.toString=function(){return this.s().toString()};
f.Nb=function(a){var b=a.h,c=a.g;return a.i?c?Wb(this,c,b):Q(this,b):c?Vb(this,c,b,0,!0):P(this,b,!0)};f.Pd=function(a,b){var c=a.h,d=a.g;return a.i?d?Tb(this,c,b,!0):Rb(this,c,b,!0):d?Sb(this,c,b,!0):R(this,c,b,!0)};f.Mb=function(){var a=this.constructor,b=yb(this.s(),Ab);a=Jb(a,b);$b(a,this);return a};
function $b(a,b){b.o&&(a.o=b.o.slice());var c=b.g;if(c){b=b.j;var d={},e;for(e in c){var k=c[e];if(k){var g=!(!b||!b[e]),h=+e;if(Array.isArray(k)){if(k.length)for(g=Wb(a,k[0].constructor,h),h=0;h<Math.min(g.length,k.length);h++)$b(g[h],k[h])}else k instanceof Db?k.j&&(d.G=Qb(a,h,k.j),k.forEach(function(l){return function(n,p){return $b(l.G.get(p),n)}}(d))):(g=Vb(a,k.constructor,h,0,g))&&$b(g,k)}d={G:d.G}}}}function T(a,b,c){return Lb(a,b)===c?c:-1}
function V(a,b,c){return Ob(a,b,void 0===c?"":c)}f.gd=function(a,b,c){return Ob(this,T(this,b,a),c)};f.ed=function(a,b,c){return Pb(this,T(this,b,a),c)};f.kd=function(a,b,c){a=T(this,b,a);return Ob(this,a,void 0===c?0:c)};f.ld=function(a,b,c){a=T(this,b,a);return Ob(this,a,void 0===c?"0":c)};f.jd=function(a,b,c){a=T(this,b,a);a=Mb(this,a);return null==a?void 0===c?0:c:a};f.md=function(a,b,c){return V(this,T(this,b,a),c)};f.fd=function(a,b){return P(this,T(this,b,a))};
f.dd=function(a,b){return Nb(this,T(this,b,a))};f.hd=function(a,b){return Mb(this,T(this,b,a))};f.nd=function(a,b,c){return Vb(this,a,T(this,c,b))};f.vd=function(a,b){return S(this,a,b,0)};f.ud=function(a,b){return S(this,a,b,0)};f.wd=function(a,b){null!=b&&0!==+b?R(this,a,b):R(this,a,void 0);return this};f.td=function(a,b){null!=b&&0!==b.length?R(this,a,b):R(this,a,void 0);return this};function W(a,b,c){b=P(b,c);null!=b&&rb(a,c,Ha(b))};function X(a){N.call(this,a,-1,ac)}X.prototype=ea(N.prototype);X.prototype.constructor=X;if(ka)ka(X,N);else for(var bc in N)if("prototype"!=bc)if(Object.defineProperties){var cc=Object.getOwnPropertyDescriptor(N,bc);cc&&Object.defineProperty(X,bc,cc)}else X[bc]=N[bc];X.g=N.prototype;f=X.prototype;f.getTenantId=function(){return Ob(this,1,0)};f.de=function(a){return S(this,1,a,0)};f.getLocale=function(){return V(this,2)};f.Md=function(a){return S(this,4,a,"")};f.Sd=function(a){return S(this,5,a,"")};
f.ee=function(a){return S(this,6,a,"")};f.getInsecureHost=function(){return V(this,7)};f.Td=function(a){return S(this,7,a,"")};f.Pc=function(){return Pb(this,8)};f.Vd=function(a){return S(this,8,a,!1)};f.Ud=function(a){return S(this,9,a,!1)};f.Jc=function(){return Q(this,10)};f.Nd=function(a){return Rb(this,10,a)};f.tc=function(a,b){return Ub(this,10,a,b)};f.yc=function(){return R(this,10,O)};f.Wd=function(a){return S(this,11,a,!1)};f.ce=function(a){return Rb(this,12,a)};
f.vc=function(a,b){return Ub(this,12,a,b)};f.Ac=function(){return R(this,12,O)};f.Qd=function(a){return Rb(this,13,a)};f.uc=function(a,b){return Ub(this,13,a,b)};f.zc=function(){return R(this,13,O)};f.Mc=function(){return V(this,14)};f.Od=function(a){return S(this,14,a,"")};f.Rc=function(){return V(this,15)};f.Xd=function(a){return S(this,15,a,"")};f.Tc=function(){return V(this,16)};f.Zd=function(a){return S(this,16,a,"")};
f.Ld=function(){var a=new mb;sb(a,1,P(this,1));W(a,this,2);W(a,this,4);W(a,this,5);W(a,this,6);W(a,this,7);qb(a,8,P(this,8));qb(a,9,P(this,9));tb(a,10,Q(this,10));qb(a,11,P(this,11));tb(a,12,Q(this,12));var b=Q(this,13);if(null!=b&&b.length){for(var c=I(a,13),d=0;d<b.length;d++)gb(a.g,b[d]);L(a,c)}W(a,this,14);W(a,this,15);W(a,this,16);if(b=this.o)for(ob(a),c=0;c<b.length;c++)nb(a,b[c]);return pb(a)};function dc(){var a=GoogleDevelopersObject;return Jb(X,a?JSON.parse(a):null)}var ac=[10,12,13];
X.prototype.v=function(a){if(null!=this){var b,c={ge:Ob(this,1,0),locale:V(this,2),wc:V(this,4),Wc:V(this,5),he:V(this,6),$c:V(this,7),zd:Pb(this,8),yd:Pb(this,9),xc:null==(b=Q(this,10))?void 0:b,Ad:Pb(this,11),fe:null==(b=Q(this,12))?void 0:b,Gc:null==(b=Q(this,13))?void 0:b,Ec:V(this,14),Hd:V(this,15),Kd:V(this,16)};a&&(c.W=this);a=c}else a=void 0;return a};var ec;function fc(a,b){this.g=b===gc?a:""}f=fc.prototype;f.Zc=!0;f.Vc=function(){return this.g.toString()};f.Yc=!0;f.Nc=function(){return 1};f.Bc=function(a,b){var c=hc.exec(ic(this).toString()),d=c[3]||"";return jc(c[1]+kc("?",c[2]||"",a)+kc("#",d,b))};f.toString=function(){return this.g+""};function ic(a){return a instanceof fc&&a.constructor===fc?a.g:"type_error:TrustedResourceUrl"}var hc=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,gc={};
function jc(a){if(void 0===ec){var b=null;var c=v.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:Da,createScript:Da,createScriptURL:Da})}catch(d){v.console&&v.console.error(d.message)}ec=b}else ec=b}a=(b=ec)?b.createScriptURL(a):a;return new fc(a,gc)}
function kc(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var k=0;k<e.length;k++){var g=e[k];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(g)))}}return b};function lc(a,b){var c=void 0;return new (c||(c=Promise))(function(d,e){function k(l){try{h(b.next(l))}catch(n){e(n)}}function g(l){try{h(b["throw"](l))}catch(n){e(n)}}function h(l){l.done?d(l.value):(new c(function(n){n(l.value)})).then(k,g)}h((b=b.apply(a,void 0)).next())})};/*

 SPDX-License-Identifier: Apache-2.0
*/
function mc(a){if(a.A&&"function"==typeof a.A)return a.A();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(Ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function nc(a){if(a.I&&"function"==typeof a.I)return a.I();if(!a.A||"function"!=typeof a.A){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if(Ba(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}}
function oc(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(Ba(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,c);else for(var d=nc(a),e=mc(a),k=e.length,g=0;g<k;g++)b.call(c,e[g],d&&d[g],a)};var pc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function qc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var k=a[c].substring(0,d);e=a[c].substring(d+1)}else k=a[c];b(k,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function rc(a,b){this.h=this.v=this.m="";this.j=null;this.o=this.i="";this.l=this.D=!1;if(a instanceof rc){this.l=void 0!==b?b:a.l;sc(this,a.m);var c=a.v;Y(this);this.v=c;c=a.h;Y(this);this.h=c;tc(this,a.j);c=a.i;Y(this);this.i=c;uc(this,vc(a.g));a=a.o;Y(this);this.o=a}else a&&(c=String(a).match(pc))?(this.l=!!b,sc(this,c[1]||"",!0),a=c[2]||"",Y(this),this.v=wc(a),a=c[3]||"",Y(this),this.h=wc(a,!0),tc(this,c[4]),a=c[5]||"",Y(this),this.i=wc(a,!0),uc(this,c[6]||"",!0),a=c[7]||"",Y(this),this.o=wc(a)):
(this.l=!!b,this.g=new xc(null,this.l))}f=rc.prototype;f.toString=function(){var a=[],b=this.m;b&&a.push(yc(b,zc,!0),":");var c=this.h;if(c||"file"==b)a.push("//"),(b=this.v)&&a.push(yc(b,zc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.j,null!=c&&a.push(":",String(c));if(c=this.i)this.h&&"/"!=c.charAt(0)&&a.push("/"),a.push(yc(c,"/"==c.charAt(0)?Ac:Bc,!0));(c=this.g.toString())&&a.push("?",c);(c=this.o)&&a.push("#",yc(c,Cc));return a.join("")};
f.resolve=function(a){var b=new rc(this),c=!!a.m;c?sc(b,a.m):c=!!a.v;if(c){var d=a.v;Y(b);b.v=d}else c=!!a.h;c?(d=a.h,Y(b),b.h=d):c=null!=a.j;d=a.i;if(c)tc(b,a.j);else if(c=!!a.i){if("/"!=d.charAt(0))if(this.h&&!this.i)d="/"+d;else{var e=b.i.lastIndexOf("/");-1!=e&&(d=b.i.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var k=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&k.push(""):".."==h?((1<k.length||
1==k.length&&""!=k[0])&&k.pop(),d&&g==e.length&&k.push("")):(k.push(h),d=!0)}d=k.join("/")}else d=e}c?(Y(b),b.i=d):c=""!==a.g.toString();c?uc(b,vc(a.g)):c=!!a.o;c&&(a=a.o,Y(b),b.o=a);return b};function sc(a,b,c){Y(a);a.m=c?wc(b,!0):b;a.m&&(a.m=a.m.replace(/:$/,""))}function tc(a,b){Y(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.j=b}else a.j=null}function uc(a,b,c){Y(a);b instanceof xc?(a.g=b,Dc(a.g,a.l)):(c||(b=yc(b,Ec)),a.g=new xc(b,a.l));return a}
f.$d=function(a,b){return uc(this,a,b)};f.Lc=function(){return wc(this.g.toString())};f.Pb=function(){return this.g.toString()};f.Yd=function(a,b){Y(this);Array.isArray(b)||(b=[String(b)]);Fc(this.g,a,b);return this};f.Sc=function(a){return this.g.A(a)};f.Xc=function(a){return(!this.h&&!a.h||this.h==a.h)&&(null==this.j&&null==a.j||this.j==a.j)};
f.Gd=function(){Y(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36);Y(this);this.g.set("zx",a);return this};f.Qb=function(a){Y(this);Gc(this.g,a);return this};f.be=function(a){this.D=a;return this};f.Bd=function(){return this.D};function Y(a){if(a.D)throw Error("Tried to modify a read-only Uri");}f.Rb=function(a){this.l=a;this.g&&Dc(this.g,a);return this};
function Hc(a){return a instanceof rc?new rc(a):new rc(a,void 0)}function wc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function yc(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Ic),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Ic(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var zc=/[#\/\?@]/g,Bc=/[#\?:]/g,Ac=/[#\?]/g,Ec=/[#\?@]/g,Cc=/#/g;function xc(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}
function Z(a){a.g||(a.g=new Map,a.h=0,a.i&&qc(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=xc.prototype;f.Kc=function(){Z(this);return this.h};f.add=function(a,b){Z(this);this.i=null;a=Jc(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function Gc(a,b){Z(a);b=Jc(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))}f.Sb=function(){this.g=this.i=null;this.h=0};f.xd=function(){Z(this);return 0==this.h};
function Kc(a,b){Z(a);b=Jc(a,b);return a.g.has(b)}f.Cc=function(a){var b=this.A();return 0<=Ia(b,a)};f.forEach=function(a,b){Z(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};f.I=function(){Z(this);for(var a=Array.from(this.g.values()),b=Array.from(this.g.keys()),c=[],d=0;d<b.length;d++)for(var e=a[d],k=0;k<e.length;k++)c.push(b[d]);return c};
f.A=function(a){Z(this);var b=[];if("string"===typeof a)Kc(this,a)&&(b=b.concat(this.g.get(Jc(this,a))));else{a=Array.from(this.g.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};f.set=function(a,b){Z(this);this.i=null;a=Jc(this,a);Kc(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};f.get=function(a,b){if(!a)return b;a=this.A(a);return 0<a.length?String(a[0]):b};
function Fc(a,b,c){Gc(a,b);if(0<c.length){a.i=null;var d=a.g,e=d.set;b=Jc(a,b);var k=c.length;if(0<k){for(var g=Array(k),h=0;h<k;h++)g[h]=c[h];k=g}else k=[];e.call(d,b,k);a.h+=c.length}}f.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.A(d);for(var k=0;k<d.length;k++){var g=e;""!==d[k]&&(g+="="+encodeURIComponent(String(d[k])));a.push(g)}}return this.i=a.join("&")};
f.Hc=function(a){Z(this);this.g.forEach(function(b,c){0<=Ia(a,c)||Gc(this,c)},this);return this};function vc(a){var b=new xc;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b}function Jc(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}function Dc(a,b){b&&!a.j&&(Z(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Gc(this,d),Fc(this,e,c))},a));a.j=b}f.Tb=function(a){for(var b=0;b<arguments.length;b++)oc(arguments[b],function(c,d){this.add(d,c)},this)};var Lc={};function Mc(a,b){var c=Lc[a];if(void 0!==c&&(!c.J||Date.now()<=c.J+3E5))return c.p;c=new Promise(function(e,k){b.onload=function(){return e(b)};b.onerror=function(g){b.parentNode&&b.parentNode.removeChild(b);k(g)};document.head.appendChild(b)});var d={J:0,p:c};c.catch(function(){return d.J=+new Date});Lc[a]=d;return c}
function Nc(a){var b=void 0===b?null:b;a=Hc(a);var c=document.createElement("script"),d=jc(a.toString());c.src=ic(d);var e;d=(c.ownerDocument&&c.ownerDocument.defaultView||window).document;var k=null===(e=d.querySelector)||void 0===e?void 0:e.call(d,"script[nonce]");(e=k?k.nonce||k.getAttribute("nonce")||"":"")&&c.setAttribute("nonce",e);b&&(c.type=b);return Mc(a.toString(),c)};function Oc(){var a=this;this.promise=new Promise(function(b,c){a.resolve=b;a.reject=c})};function Pc(){var a=this;this.h=null;this.g=new X;this.i=[];this.j=function(b){a.i.push(b)};this.m=function(){a.l()};if(v.__globalAppLoader)return v.__globalAppLoader;try{this.g=dc()}catch(b){Qc("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;Ca("__globalAppLoader",this);Ca("DevsiteApp.hasFlagAccess",function(b){return a.hasFlagAccess(b)})}Pc.prototype.o=function(){v.__globalAppLoader=null;Rc(this)};
function Rc(a){var b=document.querySelector("devsite-content");b&&(window.removeEventListener("message",a.j),b.removeEventListener("devsite-content-updated",a.m))}Pc.prototype.l=function(){Rc(this);for(var a=window,b=r(this.i),c=b.next();!c.done;c=b.next())a.dispatchEvent(c.value);this.i=[]};function Sc(){var a=[];a.push(Nc("https://www.gstatic.com/external_hosted/polymer/v2/webcomponents-lite.js"));return Promise.all(a)}
function Tc(a){var b=a.g.getLocale();a=V(a.g,4);return b&&"en"!==b?a.replace(/\.js$/,"__"+b.toLowerCase().replace("-","_")+".js"):a}Pc.prototype.getEnv=function(){if(Pb(this.g,11))return"PROD";var a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"};
Pc.prototype.hasFlagAccess=function(a){a:{var b=this.getEnv(),c=Q(this.g,13),d=new URL(document.location.toString());d=new rc(d.href);var e=Object.keys(Ea);if("PROD"!==b)for(b=r(e),e=b.next();!e.done;e=b.next())if(e=e.value,Ea[e]===a&&(e=d.g.get(e),void 0!==e)){if("true"===e){a=!0;break a}if("false"===e){a=!1;break a}}a=Array.from(c).includes(a)}return a};
function Uc(a){return lc(a,function c(){var d=this,e,k,g,h,l,n,p,G;return ya(c,function(u){switch(u.g){case 1:return u.i=2,pa(u,Sc(),4);case 4:qa(u,3);break;case 2:e=ra(u),Qc("Failed to load Devsite App dependencies: "+e.message);case 3:k=new Oc;Ca("__devsiteAppReadyResolver",k.resolve);Ca("__devsiteAppReadyPromise",k.promise);Ca("DevsiteApp.whenReady",function(){return k.promise});if(!Q(d.g,12).length){u.C(5);break}u.i=6;return pa(u,Promise.all(Q(d.g,12).map(function(J){J=Hc(J);var U=document.createElement("link");
U.setAttribute("rel","stylesheet");U.setAttribute("type","text/css");U.setAttribute("href",J.toString());return Mc(J.toString(),U)})),8);case 8:qa(u,5);break;case 6:g=ra(u),Qc("Failed to load Devsite App dependencies: "+g.message);case 5:return h=v.DevsiteAppTenantCustomized?V(d.g,6):V(d.g,5),u.i=9,pa(u,Nc(h+Tc(d)),11);case 11:qa(u,10);break;case 9:l=ra(u);if("en"===d.g.getLocale()){Qc("Failed to load Devsite App binary: "+l.message);u.C(10);break}S(d.g,2,"en","");u.i=13;return pa(u,Nc(h+V(d.g,4)),
15);case 15:qa(u,10);break;case 13:n=ra(u),Qc("Failed to load Devsite App binary: "+n.message);case 10:if(p=document,"complete"===p.readyState||"interactive"===p.readyState)u.C(0);else return G=new Oc,p.addEventListener("readystatechange",function(){"interactive"!==p.readyState&&"complete"!==p.readyState||G.resolve()}),pa(u,G.promise,0)}})})}function Qc(a){throw Error(void 0===a?"Devsite has failed to load.":a);};var Zb=new Pc,Vc=document.querySelector("devsite-content");Vc&&(window.addEventListener("message",Zb.j),Vc.addEventListener("devsite-content-updated",Zb.l.bind(Zb)));
lc(Zb,function Wc(){var b=this;return ya(Wc,function(c){var d=window;if(!("WeakMap"in d&&"performance"in d&&"now"in d.performance))return c.return();b.h||(b.h=Uc(b));return c.return(b.h)})}).then(function(){v.DevsiteAppInit||Qc("Failed to load Devsite App binary");Pb(Zb.g,9)?DevsiteAppFrameboxInit(Yb(),v.DevsiteAppAuthorizedElements):DevsiteAppInit(Yb(),v.DevsiteAppAuthorizedElements)});}).call(this);
