(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var $_=function(a,b){sY()&&(b=tY()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.bm(a,Z_(),b))},c0=function(){var a=_ds.Yh.apply(this,arguments)||this;a.eventHandler=new _ds.Sl;a.G=-1;a.D=new _ds.Sl;a.C=0;a.H=new MutationObserver(function(){return a0(a)});a.J=new _ds.Pl(function(){a0(a);b0(a)},15);a.pf=void 0;a.m=0;a.h=0;a.v=0;a.offset=0;a.updated=!1;return a},d0=function(a){window.requestAnimationFrame(function(){return a.J.Ea()})},e0=function(a,b){return(a=a.querySelector(b))?
a.getBoundingClientRect().height:0},a0=function(a){a.m=e0(a,".devsite-top-logo-row-wrapper-wrapper");a.h=e0(a,".devsite-collapsible-section");a.v=e0(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",""+a.m);a.setAttribute("bottom-row--height",""+a.h);a.setAttribute("bottom-tabs--height",""+a.v);document.body.style.setProperty("--devsite-js-header-top-row-height",a.m+"px");document.body.style.setProperty("--devsite-js-header-lower-section-height",a.h+"px");document.body.style.setProperty("--devsite-js-header-lower-tabs-height",
a.v+"px");document.body.style.setProperty("--devsite-js-header-height",a.Rh()+"px");f0(a)},g0=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){var b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},f0=function(a){var b=a.querySelector(".devsite-collapsible-section");a.offset>=a.h&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<
a.h-a.v&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.G&&(document.body.style.setProperty("--devsite-js-header-lower-tabs-offset",a.offset+"px"),_ds.bm(b,"transform","translate3d(0, -"+a.offset+"px, 0)"),b0(a),a.G=a.offset)},h0=function(a){var b=a.querySelector(".devsite-top-logo-row-middle"),c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.Yl(a.D);a.C&&window.cancelAnimationFrame(a.C);c.removeAttribute("transition");
a.removeAttribute("search-expanded");var e=new _ds.ti(b.offsetWidth,b.offsetHeight);b=new _ds.ti(c.offsetWidth,c.offsetHeight);var f=_ds.zm(c,"margin"),k="rtl"===document.documentElement.getAttribute("dir")?1:-1,l=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*k;var m=(f=a.hasAttribute("search-active"))?e:0,n=f?l:1;_ds.bm(d,{opacity:1,width:b.width+"px",height:b.height+"px"});$_(c,a.hasAttribute("search-active")?0:e);_ds.Wl(a.D,d,_ds.IM,function(){var p=a.querySelector("devsite-search"),
r=a.querySelector(".devsite-search-background");r&&(r.style.opacity="0");p&&(p.removeAttribute("transition"),$_(p,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.C=window.requestAnimationFrame(function(){c.setAttribute("transition","");if(sY()){var p=tY()?"scale3d("+n+",1,1)":"scale("+n+",1)";_ds.bm(d,Z_(),p)}$_(c,m)})}},i0=function(a,b){_ds.P(a,function d(){var e=this,f,k,l,m;return _ds.G(d,function(n){if(1==n.j){if(!e.hasAttribute("billboard"))return n.return();
f=e.querySelector("devsite-search");k=e.querySelector("devsite-search input.devsite-search-query");l=e.querySelector(".devsite-header-billboard-search devsite-search");m=null===l||void 0===l?void 0:l.querySelector("input.devsite-search-query");if(!(f&&k&&l&&m))return n.return();if(!b)return l.removeAttribute("disabled"),document.activeElement===k&&m.focus(),f.setAttribute("disabled",""),n.F(0);f.removeAttribute("disabled");return document.activeElement!==m?n.F(3):_ds.y(n,_ds.Rk(),4)}3!=n.j&&k.focus();
l.setAttribute("disabled","");_ds.z(n)})})},b0=function(a){0===a.h?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},j0=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},k0=function(a,b,c){b=b.querySelector(c);
c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.$h(a,c,b))};var sY=_ds.hi(function(){return!_ds.Ri||0<=_ds.Qb(_ds.eP,9)}),tY=_ds.hi(function(){return _ds.Ti||_ds.hF||_ds.km&&0<=_ds.Qb(_ds.eP,10)||_ds.Ri&&0<=_ds.Qb(_ds.eP,10)}),Z_=_ds.hi(function(){return _ds.Ri&&9==_ds.qm?"-ms-transform":"transform"});_ds.w(c0,_ds.Yh);_ds.g=c0.prototype;_ds.g.attributeChangedCallback=function(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;f0(this);break;case "search-active":h0(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),i0(this,a)}};
_ds.g.connectedCallback=function(){this.Z();g0(this);b0(this);a0(this);this.H.observe(this,{childList:!0,subtree:!0});f0(this);var a=_ds.yk();this.pf=_ds.ok(_ds.qk(a.href),"authuser")};_ds.g.disconnectedCallback=function(){_ds.Yl(this.eventHandler);this.H.disconnect()};
_ds.g.Z=function(){var a=this;this.eventHandler.listen(this,"devsite-search-toggle",function(b){b=b.ma;_ds.Gj(b.target,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});this.eventHandler.listen(document.body,"devsite-sitemask-hidden",function(){return document.body.removeAttribute("devsite-book-nav--open")});this.eventHandler.listen(window,"resize",function(){return d0(a)});this.eventHandler.listen(document.body,["devsite-page-loaded",
"devsite-content-updated"],function(){d0(a)});this.eventHandler.listen(this,"click",function(b){b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})};_ds.g.Rh=function(){return this.m+this.h-this.offset};_ds.g.Eq=function(){return this.m+this.h};
_ds.g.eb=function(a){this.updated=!1;if(a){k0(this,a,".devsite-header-upper-tabs");k0(this,a,".devsite-collapsible-section");k0(this,a,".devsite-product-name-wrapper");k0(this,a,"devsite-language-selector");k0(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&j0(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(j0(c,b),c=_ds.yk(),c=_ds.ok(_ds.qk(c.href),"authuser"),c!==this.pf&&(this.pf=c,b.refresh()));
_ds.$h(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.$h(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.aj(this),this.appendChild(a));g0(this);d0(this)};_ds.ja.Object.defineProperties(c0,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["offset","search-active","bottom-row--hidden"]}}});try{window.customElements.define("devsite-header",c0)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
