(function(_ds){var window=this;'use strict';var i7=function(a,b){return _ds.aa[a]=b},j7=function(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return j7.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c},Oaa=function(a,b,c,d,e,f,k,l,m,n){this.h=a;this.C=b;this.J=c;this.m=d;this.v=e;this.D=f;this.G=k;this.H=l;this.j=m;this.K=n},Paa=function(a){return new Oaa(a.m,a.v,a.H,a.h,a.j,a.C,a.K,a.G,a.D,a.J)},Qaa=function(a,b){a.J=b;return a},Raa=function(a,b){a.D=b;return a},Saa=function(a,b){a.G=
b;return a},k7=function(){this.m=null;this.v="";this.J=this.D=this.G=this.K=this.C=this.j=this.h=this.H=null},l7=function(a){var b=a.ma;b=(b=b&&"composed"in b&&b&&"composedPath"in b&&b.composed&&b.composedPath())&&0<b.length?b[0]:a.target;return Paa(Qaa(Raa(Saa((new k7).keyCode(a.keyCode||0).key(a.key||"").shiftKey(!!a.shiftKey).altKey(!!a.altKey).ctrlKey(!!a.ctrlKey).metaKey(!!a.metaKey).target(a.target),b),function(){return a.preventDefault()}),function(){return a.stopPropagation()}))},m7=function(a,
b,c){_ds.xf.call(this,a,c);this.j=b},n7=function(a){this.h=a||null;this.next=a?null:{}},o7=function(a,b){b.shift().forEach(function(c){var d=a[c];d&&(0==b.length?d.h&&delete a[c]:d.next&&(o7(d.next,b.slice(0)),_ds.lc(d.next)&&delete a[c]))})},Taa=function(a){a=a.replace(/[ +]*\+[ +]*/g,"+").replace(/[ ]+/g," ").toLowerCase();a=a.split(" ");for(var b=[],c,d=0;c=a[d];d++){var e=c.split("+"),f=null,k=null;c=0;for(var l,m=0;l=e[m];m++){switch(l){case "shift":c|=1;continue;case "ctrl":c|=2;continue;case "alt":c|=
4;continue;case "meta":c|=8;continue}e=void 0;f=l;if(!p7){k={};for(e in q7)k[q7[e]]=_ds.gF(parseInt(e,10));p7=k}k=p7[f];f=l;break}b.push({key:f,keyCode:k,modifiers:c})}return b},r7=function(a,b,c){c=c||0;b=["c_"+b+"_"+c];""!=a&&b.push("n_"+a+"_"+c);return b},s7=function(a,b){if("string"===typeof b[a])a=Taa(b[a]).map(function(e){return r7(e.key||"",e.keyCode,e.modifiers)});else{var c=b,d=a;Array.isArray(b[a])&&(c=b[a],d=0);for(a=[];d<c.length;d+=2)a.push(r7("",c[d],c[d+1]))}return a},t7=function(a,
b){32==a.D&&32==b.h&&(0,b.j)();a.D=null},u7=function(a){return _ds.rM&&a.v&&a.m},v7=function(a,b,c){var d=b.shift();d.forEach(function(e){if((e=a[e])&&(0==b.length||e.h))throw Error("Keyboard shortcut conflicts with existing shortcut: "+e.h);});b.length?d.forEach(function(e){e=e.toString();var f=new n7;e=e in a?a[e]:a[e]=f;v7(e.next,b.slice(0),c)}):d.forEach(function(e){a[e]=new n7(c)})},w7=function(a,b){for(var c=0;c<b.length;c++){var d=a[b[c]];if(d)return d}},x7=function(a,b,c){a:{var d=b.h;if(""!=
b.C){var e=b.C;if("Control"==e||"Shift"==e||"Meta"==e||"AltGraph"==e){d=!1;break a}}else if(16==d||17==d||18==d){d=!1;break a}e=b.H;var f="TEXTAREA"==e.tagName||"INPUT"==e.tagName||"BUTTON"==e.tagName||"SELECT"==e.tagName,k=!f&&(e.isContentEditable||e.ownerDocument&&"on"==e.ownerDocument.designMode);d=!f&&!k||a.L[d]||a.G?!0:k?!1:a.M&&(b.m||b.v||b.D)?!0:"INPUT"==e.tagName&&a.V[e.type]?13==d:"INPUT"==e.tagName||"BUTTON"==e.tagName?a.N?!0:32!=d:!1}if(d)if(!c&&u7(b))a.v=!1;else{c=_ds.gF(b.h);d=r7(b.C,
c,(b.J?1:0)|(b.v?2:0)|(b.m?4:0)|(b.D?8:0));e=w7(a.m,d);if(!e||1500<=Date.now()-a.C)a.m=a.j,a.C=Date.now();(e=w7(a.m,d))&&e.next&&(a.m=e.next,a.C=Date.now());e&&(e.next?(0,b.j)():(a.m=a.j,a.C=Date.now(),a.J&&(0,b.j)(),a.K&&(0,b.K)(),d=e.h,e=a.dispatchEvent(new m7("shortcut",d,b.G)),(e&=a.dispatchEvent(new m7("shortcut_"+d,d,b.G)))||(0,b.j)(),_ds.km&&(a.D=c)))}},y7=function(a,b,c){for(;0<c.length&&b;){var d=c.shift();if((d=w7(b,d))&&(0==c.length&&d.h||y7(a,d.next,c.slice(0))))return!0}return!1},z7=
function(a){_ds.hl.call(this);this.m=this.j={};this.C=0;this.L=j7(Uaa);this.V=j7(Vaa);this.J=!0;this.G=this.K=!1;this.M=!0;this.N=!1;this.D=null;this.h=a;_ds.Lf(this.h,"keydown",this.al,void 0,this);_ds.Lf(this.h,"synthetic-keydown",this.ql,void 0,this);_ds.rM&&(_ds.Lf(this.h,"keypress",this.vl,void 0,this),_ds.Lf(this.h,"synthetic-keypress",this.wl,void 0,this));_ds.Lf(this.h,"keyup",this.bl,void 0,this);_ds.Lf(this.h,"synthetic-keyup",this.rl,void 0,this)},Waa=function(a,b){return _ds.ve(a,10,b)},
Xaa=function(a){return(0,_ds.U)('<div class="devsite-popout" id="'+_ds.Y(a.id)+'"><div class="devsite-popout-result devsite-suggest-results-container" devsite-hide></div></div>')},A7=function(a){var b='<button type="submit" class="button button-white devsite-search-project-scope">';a="All results in "+_ds.gE(a);return(0,_ds.U)(b+a+"</button>")},B7=function(a,b,c){var d='<button type="submit" class="button button-white devsite-suggest-all-results">';b?(a="All results across "+_ds.gE(c),d+=a):(a='All results for "'+
_ds.gE(a)+'"',d+=a);return(0,_ds.U)(d+"</button>")},C7=function(a,b,c,d,e,f,k,l){a=(c?"":'<devsite-analytics-scope action="'+_ds.Y(_ds.JE("Restricted "+d))+'">')+'<a class="devsite-result-item-link" href="'+_ds.Y(_ds.JE(a))+'"><span class="devsite-suggestion-fragment">'+_ds.gE(b)+"</span>"+(l?'<span class="devsite-suggestion-fragment">'+_ds.gE(l)+"</span>":"")+(e?'<span class="devsite-suggestion-fragment">'+_ds.gE(e)+"</span>":"")+(_ds.jE(f)&&!k?'<span class="devsite-suggestion-fragment">'+_ds.gE(f)+
"</span>":"");c||(a+='<span class="devsite-result-item-confidential">Confidential</span>');return(0,_ds.U)(a+("</a>"+(c?"":"</devsite-analytics-scope>")))},Yaa=function(a){var b=a.projectName,c=a.qm,d=a.query,e=a.Bm;a=a.fg;b='<div class="devsite-suggest-wrapper '+(e?"":"devsite-search-disabled")+'"><div class="devsite-suggest-section"><div class="devsite-result-label">There are no suggestions for your query</div></div>'+((e?'<div class="devsite-suggest-footer">'+(c?A7(b):"")+B7(d,c,a)+"</div>":"")+
"</div>");return(0,_ds.U)(b)},Zaa=function(a){var b=a.ys,c=a.Js,d=a.Rs,e=a.projectName,f=a.qm,k=a.query,l=a.Ws,m=a.Bm;a=a.fg;var n='<div class="devsite-suggest-wrapper '+(m?"":"devsite-search-disabled")+'" tabindex="0" role="list"><div class="devsite-suggest-section">';if(0<d.length){n=n+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-partial-query" role="heading" aria-level="2">Suggested searches'+((f?'<span class="devsite-suggest-project">'+
_ds.gE(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-partial-query" action="Query Suggestion Click">');for(var p=d.length,r=0;r<p;r++){var t=d[r];n+='<div class="devsite-result-item devsite-nav-label" id="suggestion-partial-query-'+_ds.Y(r)+'" role="listitem" index=":'+_ds.Y(r)+'">'+C7(t.getPath(),t.getTitle(),_ds.re(t,14),"Query Suggestion Click")+"</div>"}n+="</devsite-analytics-scope></div>"}n+=
0<d.length&&0<b.length?'<hr role="none">':"";if(0<b.length){n=n+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-product" role="heading" aria-level="2">Pages'+((f?'<span class="devsite-suggest-project">'+_ds.gE(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-product" action="Page Suggestion Click">');p=b.length;for(r=0;r<p;r++)t=
b[r],n+='<div class="devsite-result-item devsite-nav-label" id="suggestion-product-'+_ds.Y(r)+'" role="listitem" index=":'+_ds.Y(r)+'">'+C7(t.getPath(),t.getTitle(),_ds.re(t,14),"Page Suggestion Click",void 0,_ds.M(t,4),f)+"</div>";n+="</devsite-analytics-scope></div>"}n+=0<l.length&&0<b.length+d.length?'<hr role="none">':"";if(0<l.length){n=n+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-reference" role="heading" aria-level="2">Reference'+
((f?'<span class="devsite-suggest-project">'+_ds.gE(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-reference" action="Reference Suggestion Click">');p=l.length;for(r=0;r<p;r++)t=l[r],n+='<div class="devsite-result-item devsite-nav-label" id="suggestion-reference-'+_ds.Y(r)+'" role="listitem" index=":'+_ds.Y(r)+'">'+C7(t.getPath(),t.getTitle(),_ds.re(t,14),"Reference Suggestion Click",_ds.M(t,3),
_ds.M(t,4),f,_ds.ne(t,10)[0])+"</div>";n+="</devsite-analytics-scope></div>"}n+=0<c.length&&0<b.length+d.length+l.length?'<hr role="none">':"";if(0<c.length){n+='<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-other-products" role="heading" aria-level="2"><span role="columnheader">Products</span></div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-other-products" action="Product Suggestion Click">';
b=c.length;for(d=0;d<b;d++)l=c[d],n+='<div class="devsite-result-item devsite-nav-label" id="suggestion-other-products-'+_ds.Y(d)+'" role="listitem" index=":'+_ds.Y(d)+'">'+C7(l.getPath(),l.getTitle(),_ds.re(l,14),"Product Suggestion Click")+"</div>";n+="</devsite-analytics-scope></div>"}n+="</div>"+(m?'<div class="devsite-suggest-footer">'+(f?A7(e):"")+B7(k,f,a)+"</div>":"")+"</div>";return(0,_ds.U)(n)},D7=function(){var a=_ds.Yh.call(this)||this;a.N=!1;a.J={};a.K="";a.G=null;a.m=new _ds.Sl;a.h=
null;a.M=!1;return a},bba=function(a){a.h&&(a.m.listen(a.h,"suggest-service-search",function(b){a:{var c=a.D.querySelector(".highlight");if(c&&(c=c.querySelector(".devsite-result-item-link"))){c.click();break a}E7(a,b.detail.originalEvent,!!a.G)}}),a.m.listen(a.h,"suggest-service-suggestions-received",function(b){return void $aa(a,b)}),a.m.listen(a.h,"suggest-service-focus",function(){F7(a,"cloud-track-search-focus",null);a.M=!0;G7(a,!0)}),a.m.listen(a.h,"suggest-service-blur",function(){G7(a,!1)}),
a.m.listen(a.h,"suggest-service-input",function(){!a.J["Text Entered Into Search Bar"]&&a.h.query.trim()&&(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Text Entered Into Search Bar"},bubbles:!0})),a.J["Text Entered Into Search Bar"]=!0);a.M&&(F7(a,"cloud-track-search-input",null),a.M=!1)}),a.m.listen(a.h,"suggest-service-navigate",function(b){return void aba(a,b)}),a.m.listen(document.body,"devsite-page-changed",
function(){return a.J={}}),a.h.Gm("SLASH",191));a.v&&a.m.listen(a.v,"submit",function(b){E7(a,b)});a.D&&a.m.listen(a.D,"click",function(b){var c=b.target,d=c.closest(".devsite-result-item-link");d&&(G7(a,!1),d="suggestion: "+d.getAttribute("href"),F7(a,"cloud-track-search-submit",d));c.classList.contains("devsite-search-project-scope")&&E7(a,b,!0)});a.V&&a.m.listen(a.V,"click",function(){return void G7(a,!0)});a.W&&a.m.listen(a.W,"click",function(){return void G7(a,!1)})},E7=function(a,b,c){c=void 0===
c?!1:c;var d,e;_ds.Ra(function(f){if(1==f.j){b.preventDefault();b.stopPropagation();if(!a.hasAttribute("enable-search"))return f.F(0);a.J["Full Site Search"]||(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Full Site Search"},bubbles:!0})),a.J["Full Site Search"]=!0);F7(a,"cloud-track-search-submit",a.L?"contains: "+a.L:"no match");d=c&&a.G?_ds.Gk(a.G):_ds.Gk(a.v.getAttribute("action"));e=new _ds.ak(d.href);_ds.nk(e,
"q",a.h.query);d.search=e.h.toString();return _ds.y(f,DevsiteApp.fetchPage(d.href),3)}G7(a,!1);_ds.z(f)})},aba=function(a,b){var c=b.detail;b=a.C.querySelector(".highlight");var d,e=Array.from(a.C.querySelectorAll(".devsite-result-item")),f=[],k=-1;if(b){var l=_ds.Ej(b,function(n){return n.classList.contains("devsite-suggest-section")});f=Array.from(l.querySelectorAll(".devsite-result-item"));l=_ds.ij(b.parentNode.parentNode);var m=_ds.jj(b.parentNode.parentNode);k=e.indexOf(b)}switch(c.keyCode){case 37:if(!l&&
!m)return;b&&(c=b.getAttribute("index"),m?(d=m.querySelector('[index="'+c+'"]'))||(d=_ds.Rb(Array.from(m.querySelectorAll("[index]")))):l&&((d=l.querySelector('[index="'+c+'"]'))||(d=_ds.Rb(Array.from(l.querySelectorAll("[index]"))))));break;case 39:if(!l&&!m)return;b&&(c=b.getAttribute("index"),l?(d=l.querySelector('[index="'+c+'"]'))||(d=_ds.Rb(Array.from(l.querySelectorAll("[index]")))):m&&((d=m.querySelector('[index="'+c+'"]'))||(d=_ds.Rb(Array.from(m.querySelectorAll("[index]"))))));break;case 38:b?
(d=e[k-1])||(d=_ds.Rb(f)):d=_ds.Rb(e);break;case 40:b?(d=e[k+1])||(d=f[0]):d=e[0]}b&&(b.classList.remove("highlight"),b.removeAttribute("aria-selected"));d&&(a.H.setAttribute("aria-activedescendant",d.id),d.setAttribute("aria-selected","true"),d.classList.add("highlight"),d.scrollIntoViewIfNeeded&&d.scrollIntoViewIfNeeded()||d.scrollIntoView())},F7=function(a,b,c){a.dispatchEvent(new CustomEvent(b,{detail:{type:"search",name:b,position:"nav",metadata:{eventDetail:c}},bubbles:!0}))},G7=function(a,
b){if(a.N!==b){_ds.lF(a.h,b);if(a.N=b)a.setAttribute("search-active","");else{var c=a.D.querySelector(".highlight");c&&c.classList.remove("highlight");a.removeAttribute("search-active");a.setAttribute("aria-expanded","false");_ds.aj(a.C)}a.hasAttribute("capture")||a.dispatchEvent(new CustomEvent("devsite-search-toggle",{detail:{active:b},bubbles:!0}))}},$aa=function(a,b){a.L=null;b=b.detail;var c=b.suggestions,d=b.query;if(a.h.query.toLowerCase().startsWith(d.toLowerCase()))if(c){var e=c.Zb();0<e.length&&
(b=e.filter(function(t){return t.getTitle().includes(d)}),0<b.length&&(a.L=b[0].getTitle()));b=e.filter(function(t){return 2===t.Cd()});c=e.filter(function(t){return 3===t.Cd()});var f=e.filter(function(t){return 4===t.Cd()}).slice(0,5),k=e.filter(function(t){return 1===t.Cd()});e=b.length+f.length+k.length;for(var l=_ds.q(f),m=l.next();!m.done;m=l.next())m=m.value,m.setPath(_ds.Gk((a.G||"/s/results")+"/?q="+m.getTitle()).toString());var n=d.split(cba);c.forEach(function(t){return Waa(t,_ds.ne(t,
10).filter(function(u){return n.some(function(v){return u.includes(v)})}))});l=a.getAttribute("project-name")||"";m=a.hasAttribute("project-scope");var p=a.hasAttribute("enable-search"),r=a.getAttribute("tenant-name")||"";b={ys:b,projectName:l,qm:m,Js:k,Rs:f,query:d,Ws:c,Bm:p,fg:r};0===e?_ds.$E(a.C,Yaa,b):(_ds.$E(a.C,Zaa,b),dba(a,d));a.setAttribute("aria-expanded","true");a.C.removeAttribute("hidden")}else a.C.setAttribute("hidden",""),a.setAttribute("aria-expanded","false")},dba=function(a,b){b=
new RegExp("("+_ds.xi(b)+")","ig");a=_ds.q(a.C.querySelectorAll(".devsite-suggestion-fragment"));for(var c=a.next();!c.done;c=a.next()){c=c.value;var d=c.innerHTML;d=d.replace(b,"<b>$1</b>");_ds.Km.kd(c,_ds.Ag(d))}},q7={8:"backspace",9:"tab",13:"enter",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"caps-lock",27:"esc",32:"space",33:"pg-up",34:"pg-down",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"delete",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",
59:"semicolon",61:"equals",65:"a",66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",75:"k",76:"l",77:"m",78:"n",79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z",93:"context",96:"num-0",97:"num-1",98:"num-2",99:"num-3",100:"num-4",101:"num-5",102:"num-6",103:"num-7",104:"num-8",105:"num-9",106:"num-multiply",107:"num-plus",109:"num-minus",110:"num-period",111:"num-division",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",
121:"f10",122:"f11",123:"f12",186:"semicolon",187:"equals",189:"dash",188:",",190:".",191:"/",192:"`",219:"open-square-bracket",220:"\\",221:"close-square-bracket",222:"single-quote",224:"win"};_ds.g=k7.prototype;_ds.g.keyCode=function(a){this.m=a;return this};_ds.g.key=function(a){this.v=a;return this};_ds.g.shiftKey=function(a){this.H=a;return this};_ds.g.altKey=function(a){this.h=a;return this};_ds.g.ctrlKey=function(a){this.j=a;return this};_ds.g.metaKey=function(a){this.C=a;return this};
_ds.g.target=function(a){this.K=a;return this};_ds.ub(m7,_ds.xf);var Uaa=[27,112,113,114,115,116,117,118,119,120,121,122,123,19],Vaa="color date datetime datetime-local email month number password search tel text time url week".split(" "),p7;_ds.ub(z7,_ds.hl);_ds.g=z7.prototype;_ds.g.r4=function(){return this.J};_ds.g.Ila=function(a){this.K=a};_ds.g.s4=function(){return this.K};_ds.g.Fla=function(a){this.G=a};_ds.g.m4=function(){return this.G};_ds.g.Wpa=function(a){this.M=a};_ds.g.H8=function(){return this.M};
_ds.g.Hla=function(a){this.N=a};_ds.g.xm=_ds.ca(0);_ds.g.Sta=function(a){o7(this.j,s7(0,arguments))};_ds.g.mia=function(a){return y7(this,this.j,s7(0,arguments))};_ds.g.soa=function(a){this.L=j7(a)};_ds.g.q7=function(){return _ds.kc(this.L)};
_ds.g.ua=function(){z7.Fa.ua.call(this);this.j={};_ds.Vf(this.h,"keydown",this.al,!1,this);_ds.Vf(this.h,"synthetic-keydown",this.ql,!1,this);_ds.rM&&(_ds.Vf(this.h,"keypress",this.vl,!1,this),_ds.Vf(this.h,"synthetic-keypress",this.wl,!1,this));_ds.Vf(this.h,"keyup",this.bl,!1,this);_ds.Vf(this.h,"synthetic-keyup",this.rl,!1,this);this.h=null};_ds.g.iO=function(a){return"shortcut_"+a};_ds.g.bl=function(a){a=l7(a);_ds.km&&t7(this,a);_ds.rM&&!this.v&&u7(a)&&x7(this,a,!0)};
_ds.g.rl=function(a){a=a.j();_ds.km&&t7(this,a);_ds.rM&&!this.v&&u7(a)&&x7(this,a,!0)};_ds.g.vl=function(a){a=l7(a);32<a.h&&u7(a)&&(this.v=!0)};_ds.g.wl=function(a){a=a.j();32<a.h&&u7(a)&&(this.v=!0)};_ds.g.al=function(a){x7(this,l7(a))};_ds.g.ql=function(a){x7(this,a.j())};
_ds.mF.prototype.Gm=i7(1,function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var e=this;this.h&&this.h.dispose();a&&(this.h=new z7(document),this.h.J=!1,this.h.xm.apply(this.h,[a].concat(_ds.ta(c))),this.eventHandler.listen(this.h,"shortcut",function(f){var k=document;k.activeElement&&k.activeElement===k.body&&(f.preventDefault(),_ds.lF(e,!0))}))});z7.prototype.xm=i7(0,function(a,b){v7(this.j,s7(1,arguments),a)});var cba=/[ .()<>{}\[\]\/:,]+/,eba=0;_ds.w(D7,_ds.Yh);D7.prototype.disconnectedCallback=function(){_ds.Yl(this.m);this.h&&(this.h.dispose(),this.h=null)};D7.prototype.attributeChangedCallback=function(a,b,c){switch(a){case "project-scope":this.K=c||"";this.h&&(this.h.L=this.K);break;case "url-scoped":this.G=c;break;case "disabled":this.H&&(this.H.disabled=null!==c)}};
D7.prototype.connectedCallback=function(){if(this.v=this.querySelector("form")){this.H=this.v.querySelector(".devsite-search-query");this.V=this.v.querySelector(".devsite-search-button[search-open]");this.W=this.querySelector(".devsite-search-button[search-close]");var a="devsite-search-popout-container-id-"+ ++eba;this.H.setAttribute("aria-controls",a);this.D=_ds.aF(Xaa,{id:a});this.C=this.D.querySelector(".devsite-suggest-results-container");this.v.appendChild(this.D);this.hasAttribute("project-scope")&&
(this.K=this.getAttribute("project-scope"));this.hasAttribute("url-scoped")&&(this.G=this.getAttribute("url-scoped"));this.v&&this.H&&(this.h=new _ds.mF(this,this.v,this.H),this.h.m=!0,this.h.Jh=this.hasAttribute("enable-query-completion"),this.h.xf=!0,this.h.Ih=!0,this.h.Kh=!0,this.h.L=this.K,this.h.m=this.hasAttribute("enable-suggestions"));bba(this)}};D7.prototype.X=function(a){var b=this;_ds.Ej(a.target,function(c){return c===b})||G7(this,!1)};
_ds.ja.Object.defineProperties(D7,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["project-scope","url-scoped","disabled"]}}});D7.prototype.connectedCallback=D7.prototype.connectedCallback;D7.prototype.attributeChangedCallback=D7.prototype.attributeChangedCallback;D7.prototype.disconnectedCallback=D7.prototype.disconnectedCallback;try{window.customElements.define("devsite-search",D7)}catch(a){console.warn("devsite.app.customElement.DevsiteSearch",a)};})(_ds_www);
