(function(_ds){var window=this;'use strict';var uV=function(a){return!a.classList.contains("material-icons")},vV=function(){var a=_ds.Yh.call(this)||this;a.C=new _ds.Sl;a.D=new _ds.Sl;a.m=new Set;a.h=null;"IntersectionObserver"in window&&(a.h=new IntersectionObserver(function(b){b=_ds.q(b);for(var c=b.next();!c.done;c=b.next())c=c.value,c.isIntersecting&&(c=c.target,_ds.MH(new _ds.KH,c,uV),a.m.delete(c),a.h.unobserve(c))},{rootMargin:"100%"}));return a},wV=function(a){Array.from(a.getElementsByTagName("table")).forEach(function(b){if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=
document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.bj(c,b);c.appendChild(b)}})},EV=function(a,b){var c,d,e,f,k,l,m;return _ds.Ra(function(n){if(1==n.j)return _ds.y(n,DevsiteApp.whenReady(),2);c=_ds.yk();d=DevsiteApp.getInsecureHost();e=b.ma;if(e.origin!==c.origin&&d&&e.origin!==d)return n.return();try{f=_ds.Oe(_ds.Tm,e.data)}catch(p){return n.return()}k=_ds.qe(f,
1,0);if(4===k)return xV(a,e),n.return();l=f.getName();if(!l)return n.return();if(m=a.querySelector('devsite-iframe iframe[name="'+l+'"]'))switch(k){case 5:yV(f,m);break;case 8:zV(e,f,c);break;case 1:AV(e,f,c);break;case 6:case 7:BV(k,c,f);break;case 9:CV(a,f);break;case 10:DV(f,c)}_ds.z(n)})},yV=function(a,b){var c,d,e,f;_ds.Ra(function(k){c=_ds.Si(document).y;d=_ds.Te(a,4);e=_ds.Te(a,3);f=_ds.mj(b);d&&f.setAttribute("width",d+"px");e&&f.setAttribute("height",e+"px");window.requestAnimationFrame(function(){window.scrollTo(_ds.Si(document).x,
c)});_ds.z(k)})},xV=function(a,b){var c,d,e;_ds.Ra(function(f){if(c=FV(a,b.source)){d="goog_"+_ds.dn++;c.setAttribute("name",d);var k=_ds.Um(3);e=_ds.Ze(k,2,d);(k=b.source)&&k.postMessage(_ds.Ne(e),"*")}_ds.z(f)})},zV=function(a,b,c){var d;_ds.Ra(function(e){var f=_ds.Vm(_ds.Um(8),_ds.M(b,8));d=_ds.Ze(f,6,c.toString());(f=a.source)&&f.postMessage(_ds.Ne(d),"*");_ds.z(e)})},AV=function(a,b,c){var d;_ds.Ra(function(e){var f=_ds.Vm(_ds.Um(2),_ds.M(b,8));d=_ds.Ze(f,7,c.search+c.hash);(f=a.source)&&f.postMessage(_ds.Ne(d),
"*");_ds.z(e)})},BV=function(a,b,c){var d,e,f;_ds.Ra(function(k){d=c.getTitle();e=new URL(c.getUrl(),b.origin);f=window.location.origin+window.location.pathname+e.search+e.hash;6===a?window.history.pushState({},d,f):window.history.replaceState({},d,f);_ds.z(k)})},CV=function(a,b){var c,d,e,f;_ds.Ra(function(k){c=_ds.M(b,9);d=JSON.parse(_ds.M(b,10));"cloudtrackEvent"===c&&d?(e=d,f={eventData:e},a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:f,bubbles:!0}))):"devsite-apix"===
c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}));_ds.z(k)})},DV=function(a,b){var c,d;_ds.Ra(function(e){if(c=a.getUrl())d=new URL(c,b.origin),c.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?DevsiteApp.scrollToAnchor(d.hash,!0):DevsiteApp.fetchPage(d.href);_ds.z(e)})},FV=function(a,b){var c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(function(d){_ds.qj(d)===b&&(c=d)});return c},IV=function(a){a.v=a.querySelector(".devsite-article-body");
a.v&&GV(a);a.h&&a.h.disconnect();a.m.clear();wV(a);var b=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));if("docs"===document.body.getAttribute("layout")&&a.v){var c=Array.from(a.v.querySelectorAll("h1, h2, h3, h4, h5, h6"));b.push.apply(b,_ds.ta(c))}a.m.clear();a.m=new Set(b);if(_ds.yk().hash){b=new _ds.KH;c=_ds.q(a.m);for(var d=c.next();!d.done;d=c.next())_ds.MH(b,d.value,uV)}else HV(a,a.m);a.dispatchEvent(new CustomEvent("devsite-content-updated",
{bubbles:!0}))},GV=function(a){"full"===document.body.getAttribute("layout")&&(a=a.v.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(function(b){b.removeAttribute("tabindex")})},HV=function(a,b){a.h&&b.forEach(function(c){a.h.observe(c)})};_ds.w(vV,_ds.Yh);vV.prototype.connectedCallback=function(){var a=this;this.C.listen(window,"message",function(b){return EV(a,b)});IV(this)};
vV.prototype.disconnectedCallback=function(){this.h&&this.h.disconnect();this.m.clear();_ds.Yl(this.C);_ds.Yl(this.D)};vV.prototype.eb=function(a){var b=this;a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-google-survey"].forEach(function(c){_ds.$h(b,b.querySelector(c),a.querySelector(c))}),IV(this))};vV.prototype.updateContent=vV.prototype.eb;vV.prototype.disconnectedCallback=vV.prototype.disconnectedCallback;vV.prototype.connectedCallback=vV.prototype.connectedCallback;try{window.customElements.define("devsite-content",vV)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
