(function(_ds){var window=this;'use strict';var gU=function(){return(0,_ds.U)('<input type="checkbox" class="bookmark-checkbox">')},hU=function(a){var b=a.isSignedIn;a=a.qb;var c='<devsite-dialog class="devsite-bookmark-dialog" id="devsite-bookmark-dialog"><div class="devsite-dialog-contents">';a&&(c+='<h3 class="no-link">',c=(b?c+"Create a Google Developer Profile to bookmark":c+"Sign in to bookmark")+"</h3>");c+="<p>";c=(b?a?c+"Save your frequently visited pages with a Google Developer Profile.":c+'This account is not eligible for Developer Profiles. <a href="https://developers.google.com#i%E2%80%99m_unable_to_create_a_profile_with_my_g_suite_account_why_is_that" target="_blank">Learn more</a>':
c+"You need to be signed in to save your frequently visited pages with a Google Developer Profile.")+"</p>";b&&a&&(c+="<p>Create your Google Developer Profile.</p>");c+='</div><div class="devsite-dialog-buttons">';c=b?a?c+'<button class="button-primary create-profile">Create profile':c+'<button class="button-primary change-account">Change account':c+'<button class="button button-primary sign-in-button">Sign in';return(0,_ds.U)(c+'</button><button class="button devsite-dialog-close">Dismiss</button></div></devsite-dialog>')},
iU=function(a){var b=a.hb;a='<devsite-dialog class="devsite-bookmark-dialog" id="devsite-bookmark-create-profile-dialog"><div class="create-profile-spinner"><devsite-spinner size="48"></devsite-spinner></div><div class="devsite-dialog-contents"><h3 class="no-link">Would you like to receive emails regarding new features, events, badges, content, and research opportunities?</h3><input type="checkbox" id="devsite-bookmark-create-profile-email-opt-in"><label for="devsite-bookmark-create-profile-email-opt-in">Yes, sign me up for Google Developer emails.</label><p class="account-note">';
b='By creating a Developer Profile, you agree to the <a href="'+(_ds.Y(_ds.JE(b))+'">Content Policy</a>. Google\'s <a href="https://policies.google.com/terms">Terms of Service</a> and <a href="https://policies.google.com/privacy">Privacy Policy</a> apply to your use of this service. The name on your Google Account will be used in your Google Developer Profile. It may appear where you contribute and can be changed at any time.');a=a+b+'</p></div><div class="devsite-dialog-buttons"><button class="button-primary create-profile">Create Profile';
a+='</button><button class="button devsite-dialog-close">';a+="Dismiss";a+="</button></div></devsite-dialog>";return(0,_ds.U)(a)},jU=function(a){a='<devsite-dialog class="devsite-bookmark-dialog" id="devsite-bookmark-error-dialog"><div class="devsite-dialog-contents"><h3 class="no-link">Something went wrong</h3><p>'+(_ds.gE(a.error)+'</p></div><div class="devsite-dialog-buttons"><button class="button devsite-dialog-close">');return(0,_ds.U)(a+"Dismiss</button></div></devsite-dialog>")},kU=function(){var a=
_ds.Yh.call(this,["devsite-snackbar","devsite-dialog"])||this;a.eventHandler=new _ds.Sl;a.D=null;a.C=null;a.G=null;a.h=null;a.m=null;a.v=!1;return a},oU=function(a){return _ds.P(a,function c(){var d=this,e,f,k,l,m;return _ds.G(c,function(n){switch(n.j){case 1:d.toggleAttribute("saved");if(!d.v){lU(d,"Page unsaved.");n.F(2);break}return _ds.y(n,(0,_ds.Ou)("/saved-pages",void 0,void 0,!1,!0),3);case 3:e=n.h,lU(d,"Page saved.","View Saved Pages",e);case 2:return _ds.y(n,(0,_ds.ao)(),4);case 4:return f=
n.h,_ds.y(n,f.isSignedIn(),5);case 5:k=n.h;l=!0;if(!k){n.F(6);break}return _ds.y(n,d.qb(),7);case 7:l=n.h;case 6:if(!l){n.F(8);break}return _ds.y(n,d.Y(),9);case 9:m=n.h;if(!m){n.F(8);break}return _ds.y(n,mU(d,m),11);case 11:return n.return();case 8:d.G=nU(d,k,l),d.G.setAttribute("open",""),_ds.z(n)}})})},lU=function(a,b,c,d){a.dispatchEvent(new CustomEvent("devsite-show-custom-snackbar-msg",{detail:{msg:b,linkText:c,href:null===d||void 0===d?void 0:d.href,showClose:!1},bubbles:!0}))},pU=function(a){var b;
if(a.C){var c=(a.C.checked=a.v)?"Remove bookmark":"Add bookmark";a.setAttribute("data-title",c);null===(b=a.C)||void 0===b?void 0:b.setAttribute("aria-label",c)}},nU=function(a,b,c){var d=document.body.querySelector("#devsite-bookmark-dialog");d||(d=_ds.aF(hU,{isSignedIn:b,qb:c}),document.body.appendChild(d),(b=d.querySelector(".create-profile"))&&a.eventHandler.listen(b,"click",function(){return _ds.P(a,function f(){var k=this;return _ds.G(f,function(l){if(1==l.j)return null===d||void 0===d?void 0:
d.removeAttribute("open"),_ds.y(l,qU(k),2);k.h=l.h;k.h.setAttribute("open","");_ds.z(l)})})}),(b=d.querySelector(".sign-in-button"))&&a.eventHandler.listen(b,"click",function(e){return _ds.P(a,function k(){var l,m;return _ds.G(k,function(n){if(1==n.j)return e.preventDefault(),e.stopPropagation(),l=new _ds.ak(_ds.yk().href),l.h.add("bookmark",!0),_ds.Ak(l.toString(),!0,!1),_ds.y(n,(0,_ds.ao)(),2);m=n.h;return _ds.y(n,m.signIn(),0)})})}),(b=d.querySelector(".change-account"))&&a.eventHandler.listen(b,
"click",function(e){return _ds.P(a,function k(){var l,m;return _ds.G(k,function(n){if(1==n.j)return e.preventDefault(),e.stopPropagation(),l=new _ds.ak(_ds.yk().href),l.h.add("bookmark",!0),_ds.Ak(l.toString(),!0,!1),_ds.y(n,(0,_ds.ao)(),2);m=n.h;return _ds.y(n,m.changeAccount(),0)})})}),(b=d.querySelector(".devsite-dialog-close"))&&a.eventHandler.listen(b,"click",function(){a.toggleAttribute("saved");rU(a,"Callout Profile dismissed")}));return d},qU=function(a){return _ds.P(a,function c(){var d=
this,e,f,k,l,m;return _ds.G(c,function(n){if(1==n.j)return e=d,rU(d,"Callout Profile displayed"),(f=document.body.querySelector("#devsite-bookmark-create-profile-dialog"))?n.F(2):_ds.y(n,(0,_ds.Mu)(),3);2!=n.j&&(k=n.h.href,f=_ds.aF(iU,{hb:k}),document.body.appendChild(f),(l=f.querySelector(".create-profile"))&&d.eventHandler.listen(l,"click",function(){e.createProfile()}),(m=f.querySelector(".devsite-dialog-close"))&&d.eventHandler.listen(m,"click",function(){e.toggleAttribute("saved");rU(e,"Callout Profile dismissed")}));
return n.return(f)})})},sU=function(a,b){rU(a,"Callout Profile error");a=document.body.querySelector("#devsite-bookmark-error-dialog");a||(a=_ds.aF(jU,{error:b}),document.body.appendChild(a));return a},mU=function(a,b){return _ds.P(a,function d(){var e,f=this,k,l,m,n;return _ds.G(d,function(p){switch(p.j){case 1:if(null===b||void 0===b||!b.profileId)return p.return();e="SAVE_STATE_UNKNOWN";e=f.v?"SAVED":"UNSAVED";k=_ds.yk().href;_ds.A(p,2);return _ds.y(p,(0,_ds.Vu)(k),4);case 4:k=p.h;_ds.E(p,3);break;
case 2:_ds.F(p);case 3:return l=new _ds.Cu,_ds.A(p,5),_ds.y(p,l.Ee({path:k,status:e,profileId:b.profileId}),7);case 7:_ds.E(p,6);break;case 5:_ds.F(p),f.m=sU(f,"There was an issue saving the page."),f.m.setAttribute("open",""),f.toggleAttribute("saved");case 6:return f.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:f.v?"Saving Page to Profile":"Removing Saved Page from Profile",label:"Saving Widget"},bubbles:!0})),m=document.querySelector("devsite-user#devsite-user"),
_ds.y(p,(0,_ds.Ou)("/saved-pages",null===b||void 0===b?void 0:b.profileId,null===b||void 0===b?void 0:b.vanityId,!1,!0),8);case 8:n=p.h;if(!f.v||window.sessionStorage.getItem("devsite_bookmark_popout_shown")){p.F(0);break}return _ds.y(p,null===m||void 0===m?void 0:m.He("view-bookmarked-pages",n),10);case 10:window.sessionStorage.setItem("devsite_bookmark_popout_shown","true"),_ds.z(p)}})})},tU=function(a){return _ds.P(a,function c(){var d,e=this,f,k,l,m,n,p,r;return _ds.G(c,function(t){switch(t.j){case 1:d=
new _ds.ak(_ds.yk().href);if(!_ds.uk(d.h,"bookmark")){t.F(2);break}return _ds.y(t,oU(e),3);case 3:return d.h.remove("bookmark"),_ds.Ak(d.toString(),!0,!1),t.return();case 2:return _ds.y(t,(0,_ds.ao)(),4);case 4:return f=t.h,_ds.y(t,f.isSignedIn(),5);case 5:return(k=t.h)?_ds.y(t,e.Y(),6):t.return();case 6:l=t.h;if(null===l||void 0===l||!l.profileId)return t.return();m=_ds.yk().href;_ds.A(t,7);return _ds.y(t,(0,_ds.Vu)(m),9);case 9:m=t.h;_ds.E(t,8);break;case 7:_ds.F(t);case 8:return n=(null===l||void 0===
l?void 0:l.profileId)||"",p=new _ds.Cu,_ds.A(t,10),_ds.y(t,p.getPath({path:m,profileId:n}),12);case 12:r=t.h;if("SAVED"===(null===r||void 0===r?void 0:r.saveStatus))return e.setAttribute("saved",""),t.return();_ds.E(t,0);break;case 10:_ds.F(t),_ds.z(t)}})})},rU=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"Saving Widget Callout"},bubbles:!0}))};_ds.w(kU,_ds.Yh);_ds.g=kU.prototype;
_ds.g.connectedCallback=function(){var a,b;return _ds.P(this,function d(){var e,f=this;return _ds.G(d,function(k){if(1==k.j){e=document.body.querySelector(".devsite-page-title,.devsite-playlist-title,.devsite-quiz-title,[layout=docs] .devsite-article h1:first-of-type");if(!e)return f.remove(),k.return();if(e&&f.previousElementSibling!==e)return null===(a=e.parentElement)||void 0===a?void 0:a.insertBefore(f,e.nextSibling),k.return();f.classList.add("show");return _ds.y(k,tU(f),2)}_ds.$E(f,gU);f.D=
document.body.querySelector(".devsite-article");null===(b=f.D)||void 0===b?void 0:b.setAttribute("has-bookmark","");f.C=f.querySelector(".bookmark-checkbox");pU(f);f.Z();_ds.z(k)})})};_ds.g.disconnectedCallback=function(){var a;_ds.Yl(this.eventHandler);_ds.ej(this.G);_ds.ej(this.h);_ds.ej(this.m);this.C=null;null===(a=this.D)||void 0===a?void 0:a.removeAttribute("has-bookmark")};_ds.g.attributeChangedCallback=function(a,b,c){"saved"===a&&(this.v=null!==c,pU(this))};
_ds.g.Z=function(){var a=this;this.eventHandler.listen(this,"change",function(){oU(a)})};
_ds.g.createProfile=function(){var a,b,c,d,e,f;return _ds.P(this,function l(){var m,n,p=this,r,t,u,v,x;return _ds.G(l,function(B){switch(B.j){case 1:return m=document.querySelector("devsite-user#devsite-user"),_ds.y(B,null===m||void 0===m?void 0:m.getAccountName(),2);case 2:if(n=B.h){B.F(3);break}return _ds.y(B,null===m||void 0===m?void 0:m.getAccountEmail(),4);case 4:(n=B.h)&&(n=n.charAt(0));case 3:if(!n)return null===(a=p.h)||void 0===a?void 0:a.removeAttribute("open"),p.m=sU(p,"There was an issue getting your account information."),
p.m.setAttribute("open",""),p.toggleAttribute("saved"),B.return();r=null===(b=p.h)||void 0===b?void 0:b.querySelector("#devsite-bookmark-create-profile-email-opt-in");t=!(!r||!r.checked);null===(c=p.h)||void 0===c?void 0:c.classList.add("loading");u=new _ds.Eu;_ds.A(B,5);return _ds.y(B,_ds.Gu(u,n,t,!0),7);case 7:return rU(p,"Callout Profile created"),null===(d=p.h)||void 0===d?void 0:d.removeAttribute("open"),_ds.y(B,p.Y(),8);case 8:v=B.h;if(!v){B.F(9);break}return _ds.y(B,mU(p,v),9);case 9:_ds.E(B,
6);break;case 5:x=_ds.F(B),null===(e=p.h)||void 0===e?void 0:e.removeAttribute("open"),p.m=sU(p,""+x),p.m.setAttribute("open",""),p.toggleAttribute("saved");case 6:null===(f=p.h)||void 0===f?void 0:f.classList.remove("loading"),_ds.z(B)}})})};
_ds.g.qb=function(){var a;return _ds.P(this,function c(){var d,e,f,k;return _ds.G(c,function(l){switch(l.j){case 1:return _ds.y(l,(0,_ds.ao)(),2);case 2:return d=l.h,_ds.y(l,d.isSignedIn(),3);case 3:e=l.h;if(!e)return l.return(!1);f=new _ds.Au;k=null;_ds.A(l,4);return _ds.y(l,f.Va(),6);case 6:k=l.h;_ds.E(l,5);break;case 4:_ds.F(l);case 5:return l.return("ELIGIBILITY_ELIGIBLE"===(null===(a=null===k||void 0===k?void 0:k.createProfile)||void 0===a?void 0:a.status))}})})};
_ds.g.Y=function(){return _ds.P(this,function b(){var c=this,d,e,f;return _ds.G(b,function(k){switch(k.j){case 1:return _ds.y(k,c.qb(),2);case 2:d=k.h;if(!d)return k.return(null);e=new _ds.Eu;f=null;_ds.A(k,3);return _ds.y(k,e.Y(),5);case 5:f=k.h;_ds.E(k,4);break;case 3:_ds.F(k);case 4:return k.return(f)}})})};_ds.ja.Object.defineProperties(kU,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["saved"]}}});try{window.customElements.define("devsite-bookmark",kU)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookmark",a)};})(_ds_www);
