
trigger:
  none

pool:
  vmImage: 'ubuntu-18.04'

strategy:
  matrix:
    debian:
      img: 'vvaltchev/debian:latest'
    fedora:
      img: 'vvaltchev/fedora:latest'
    arch:
      img: 'vvaltchev/archlinux:latest'
    opensuse:
      img: 'vvaltchev/opensuse:latest'


container: $[ variables['img'] ]

variables:
  CI: 1
  RUNNING_IN_CI: 1
  GTEST_SHUFFLE: 0

steps:
  - script: printenv
    displayName: Dump env
  - script: sudo -E ./scripts/build_toolchain
    displayName: "[toolchain] Default run"
  - bash: sudo ./scripts/tc/$(cat toolchain2/.distro)/install_pkg -ci python3
    displayName: Install Python 3
  - script: sudo -E ./scripts/build_toolchain -s build_gtest
    displayName: "[toolchain] Build gtest"
  - script: sudo -E ./scripts/build_toolchain -s build_gtest_arch
    displayName: "[toolchain] Build gtest_arch"
  - script: sudo -E ./scripts/build_toolchain -s build_lcov
    displayName: "[toolchain] Build lcov"
  - script: sudo -E ./scripts/build_toolchain -s build_libmusl
    displayName: "[toolchain] Build libmusl"
  - script: sudo -E ./scripts/build_toolchain -s build_ncurses
    displayName: "[toolchain] Build ncurses"
  - script: sudo -E ./scripts/build_toolchain -s build_tcc
    displayName: "[toolchain] Build tcc"
  - script: sudo -E ./scripts/build_toolchain -s build_micropython
    displayName: "[toolchain] Build micropython"
  - script: sudo -E ./scripts/build_toolchain -s build_vim
    displayName: "[toolchain] Build vim"
  - script: make -j
    displayName: Build the kernel
  - script: make -j gtests
    displayName: Build the unit tests
  - script: ./build/gtests
    displayName: Run the unit tests
  - script: ./tests/system/runners/ci_run_all_tests_wrapper -c
    displayName: Run the system tests
