"use strict"
;__filename="background/help_dialog.js",define(["require","exports","./store","./utils","./browser","./normalize_urls","./i18n"],(e,t,a,n,r,o,i)=>{
Object.defineProperty(t,"__esModule",{value:!0}),t.ea=t.Un=void 0;let l,s=null,c=new Map,u=e=>{
let t=e.indexOf("</style>")+8,r=e.slice(0,t),i=e.slice(t).trim();{let e=r.match(/<style.*?>/)
;i=r.slice(0,e.index).trim()+i,r=r.slice(e.index+e[0].length,-8)}i=i.replace(/\$(\w+)/g,(e,t)=>{var a
;return(a=l.get(t))!==null&&a!==void 0?a:t});let s=n.Vn({homePage:a.Q.ta,version:a.Q.aa,
release:o._r("vimium://release"),
reviewPage:"https://addons.mozilla.org/firefox/addon/vimium-c/reviews/?src=external-help-dialog",
webStore:l.get("addons"),browserHelp:"https://support.mozilla.org/kb/keyboard-shortcuts-perform-firefox-tasks-quickly"})
;return i=i.replace(/\{\{(\w+)}}/g,(e,t)=>s[t]||e),[r,i]};t.Un=(e,r)=>{l=a.na[1],s&&!a.na[0]||(s=u(a.na[0]),a.na[0]="")
;let o=new Map,c=!e;r=e||!!r,a.qn.forEach((e,n)=>{if(/^<v-.\w*>/.test(n))return;let r=e.ra;e.Ln===38&&e.On&&(a.oa(e),
r=e.ra);let i=t.ea(r),l=o.get(i);l?l.push([n,e]):o.set(i,[[n,e]])});let p=e?" "+l.get("cmdList"):"",g=n.Vn({
title2:p&&(p.includes(" ",1)?p:p.trimLeft()),name2:" - "+i.Fe("name").split(" - ")[1],
tip:r&&l.get("tipClickToCopy")||"",lbPad:r?'\n\t\t<tr><td class="HelpTd TdBottom">&#160;</td></tr>':""
}),m=s[1].replace(/\{\{(\w+)}}/g,(e,t)=>{var a;return(a=g[t])!==null&&a!==void 0?a:d(t,o,c,r)});return{h:s[0],b:m}}
;let includes=(e,t)=>e.includes(t),startsWith=(e,t)=>e.startsWith(t),endsWith=(e,t)=>e.endsWith(t)
;t.ea=e=>(includes(e,"Mode")&&includes(e,".activate")&&(e=includes(e,"ModeTo")?e.replace("ModeTo",""):e.replace("Mode","")),
endsWith(e,"Unhover")?e=e.replace("Unhover","Leave"):endsWith(e,"Goto")?e=e.replace("Goto",""):e==="clearContentSetting"?e=`${e}s`:includes(e,"CS")?e=startsWith(e,"clear")?"clearContentSettings":e.replace("CS","ContentSetting"):includes(e,"vateUrl")?e=e.replace("vateUrl","vateEditUrl"):endsWith(e,"TabSelection")?e=e.replace("TabSelection","Tabs"):e==="quickNext"?e="nextTab":e==="newTab"?e="createTab":e==="closeSomeOtherTabs"?e="closeOtherTabs":e==="simBackspace"?e="simulateBackspace":e==="showHUD"||e==="showHud"?e="showTip":e==="wait"&&(e="blank"),
e);let d=(e,t,a,r)=>{let o=l.get("cmdParams")||" (use *)",i="",s=g[e];for(let e=0;e<s.length;e++){let u=s[e],d=t.get(u)
;if(a&&!d)continue;let g=e<s.length-1&&s[e+1]===1;g&&e++;let m=e<s.length-1?s[e+1]:"a",b=m[0]==="$"?(e++,
m.slice(1)):"",v=-2,k="",T=c.get(u)
;if(T||(T=[l.get(u).replace("<","&lt;").replace(">","&gt;"),b?o.replace("*",()=>b):" "],c.set(u,T)),d&&d.length>0){
k='\n\t\t<span class="HelpKey">';for(let e=0;e<d.length;e++){if(v>42&&e<d.length-1){
k+=`</span>\n\t<span>+ ${d.length-e} \u2026`;break}let t=d[e];v>=0&&(k+='</span> <span class="HelpKey">'),k+=n.Qr(t[0]),
v+=t[0].length+2}k+="</span>\n\t"}let $=r?T[0]+T[1]:T[0];v<=12?i+=p(g,k,$,r?u:""):(i+=p(g,k,"",""),i+=p(g,"",$,r?u:""))}
return i},p=(e,t,a,n)=>{let r=e?'<tr class="HelpAdv">\n\t':"<tr>\n\t";return a?(r+='<td class="HelpTd HelpKeys">',r+=t,
r+='</td>\n\t<td class="HelpTd HelpCommandInfo">',r+=a,n&&(r+='<span class="HelpCommandName" role="button">(',r+=n,
r+=")</span>\n\t")):(r+='<td class="HelpTd HelpKeys HelpLongKeys" colspan="2">',r+=t),r+"</td>\n</tr>\n"},g={
pageNavigation:["LinkHints.activate",'$button=""/right, touch=false/true/"auto"',"LinkHints.activateOpenInNewTab","LinkHints.activateOpenInNewForegroundTab","LinkHints.activateWithQueue","scrollDown","$keepHover=true|false|auto|never","scrollUp","$keepHover=true|false|auto|never","scrollLeft","scrollRight","scrollToTop","scrollToBottom","scrollToLeft",1,"scrollToRight",1,"scrollPageDown","scrollPageUp","scrollPxDown",1,"scrollPxUp",1,"scrollPxLeft",1,"scrollPxRight",1,"scrollFullPageDown","scrollFullPageUp","scrollSelect",1,'$dir=down|up, position=""|begin|end',"reload","$hard","reloadTab","reloadGivenTab",1,"$hard","zoom","$in, out, reset","zoomIn",1,"zoomOut",1,"zoomReset",1,"toggleUrl",1,"toggleViewSource",1,"copyCurrentUrl","$type=url/title/frame, decoded","copyCurrentTitle","switchFocus",'$flash, select=""/all/all-line/start/end',"focusInput",'$keep, select=""/all/all-line/start/end',"LinkHints.activateCopyLinkUrl","LinkHints.activateCopyLinkText","$join:boolean/string","openCopiedUrlInCurrentTab","openCopiedUrlInNewTab","goUp","$trailingSlash=null/true/false","goToRoot","LinkHints.activateCopyImage",1,"$richText=safe","LinkHints.activateDownloadImage",1,"LinkHints.activateOpenImage",1,"$auto=true","LinkHints.activateDownloadLink",1,"LinkHints.activateOpenIncognito",1,"LinkHints.activateOpenUrl",1,"LinkHints.activateFocus","LinkHints.activateHover",1,"$","LinkHints.activateLeave",1,"LinkHints.unhoverLast",1,"LinkHints.activateSearchLinkText","LinkHints.activateEdit","LinkHints.activateSelect","$visual=true, caret, then:{}","LinkHints.click","$direct=true|element|sel|focus|click|sel,focus,click","simulateBackspace","dispatchEvent",1,'$key="key,keyCode,code",init:{}',"goNext","$sed=true, patterns:string, rel:string, noRel, isNext","goPrevious","nextFrame","mainFrame","parentFrame","enterInsertMode","$key:string, unhover, reset","enterVisualMode","enterVisualLineMode","Marks.activateCreate","$swap","Marks.activate","$prefix=true, swap, mapKey","Marks.clearLocal",1,"Marks.clearGlobal",1,"openUrl","$url:string, urls:string[], reuse=newFg/current/newBg/reuse, incognito, window, position","focusOrLaunch",1,"$url:string, prefix"],
vomnibarCommands:["Vomnibar.activate",'$keyword="", url:boolean/string',"Vomnibar.activateInNewTab","$keyword, url","Vomnibar.activateBookmarks","Vomnibar.activateBookmarksInNewTab","Vomnibar.activateHistory","Vomnibar.activateHistoryInNewTab","Vomnibar.activateTabs","Vomnibar.activateEditUrl",1,"Vomnibar.activateEditUrlInNewTab",1,"LinkHints.activateOpenVomnibar","$url, newtab, then:{}","toggleVomnibarStyle",1,"$style=dark, current"],
historyNavigation:["goBack","$reuse=current/newBg/newFg","goForward","reopenTab",1],
findCommands:["enterFindMode","$last, selected=true","performFind","performBackwardsFind","performAnotherFind","findSelected","$selected=line/any/auto-line","findSelectedBackwards","clearFindHistory",1],
tabManipulation:["nextTab","$blur, wrap=true","previousTab","$blur, wrap=true","firstTab","lastTab","createTab","duplicateTab","removeTab",'$keepWindow=""/always, mayClose, goto=""/left/right/previous',"removeRightTab",1,"restoreTab","restoreGivenTab",1,"discardTab",1,"moveTabToNextWindow",1,"$last, position, right=true, tabs","moveTabToNewWindow",1,"$limited=null/true/false","moveTabToIncognito",1,"joinTabs","sortTabs","$sort=recency|createTime","togglePinTab","toggleMuteTab","$all, other","visitPreviousTab","$blur, acrossWindows, onlyActive","closeTabsOnLeft",1,"$$count=0","closeTabsOnRight",1,"$$count=0","closeOtherTabs",1,'$filter=""/url/url+hash/url+title',"moveTabLeft",1,"$group=true","moveTabRight",1,"$group=true","toggleContentSetting",1,"$type=images","enableContentSettingTemp",1,"clearContentSettings",1,"copyWindowInfo",1,'$format="${title}: ${url}", join:true/string, decoded',"captureTab","toggleWindow",'$states="normal,maximized"'],
misc:["showHelp","autoCopy","$text: string, url, decoded","autoOpen","searchAs","$copied=true, selected=true","searchInAnother","$keyword, reuse=current/newFg/newBg/reuse","showTip","$text:string","openBookmark","$title, path","addBookmark",1,"$folder:string","toggleStyle",1,"$id/selector:string, css: string","toggleLinkHintCharacters",1,"$value:string","editText",1,"$run:string, dom=false","toggleSwitchTemp",1,"$key:string, [value:any]","passNextKey",1,"$expect:string, normal","debugBackground",1,"reset",1,"runKey",1,"$expect:Envs, keys:KeySequence[]|string","sendToExtension",1,"$id:string, data:any, raw","confirm",1,"$ask:string, $then, $else","blank",1]
};g.tabManipulation.push("toggleReaderMode",1)});