(function(_ds){var window=this;'use strict';var AT=function(){return(0,_ds.U)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},BT=function(){return(0,_ds.U)('<div class="devsite-book-nav-blur"></div>')},DT=function(){var a=_ds.Yh.call(this)||this;a.C=!1;a.m=null;a.J=null;a.v=null;a.G=null;a.K=[];a.eventHandler=new _ds.Sl;a.N=function(){};a.D=new Set;a.W=!1;a.L=!1;a.background=document.createElement("div");a.background.classList.add("devsite-book-nav-bg");
a.h=_ds.aF(AT);a.H=_ds.aF(BT);a.V=new Promise(function(b){a.N=b});a.M=new _ds.Pl(function(){a.C&&CT(a)},20);return a},ET=function(a){a.K=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},FT=function(a){for(var b,c=_ds.q(a.K),d=c.next();!d.done;d=c.next())d.value.classList.toggle("hidden",!(null===(b=a.v)||void 0===b||!b.value))},GT=function(a){if(a.querySelector("mark")){a=Array.from(a.querySelectorAll(".devsite-nav-text > mark"));
a=_ds.q(a);for(var b=a.next();!b.done;b=a.next()){b=b.value.parentElement;var c=null===b||void 0===b?void 0:b.textContent;b&&c&&_ds.Km.kd(b,_ds.yg.h(c))}}},IT=function(a,b,c){c=void 0===c?!0:c;b=Array.from((void 0===b?a:b).querySelectorAll(".devsite-nav-title"));a.D=new Set(b);if(!_ds.yk().hash&&c)HT(a,a.D);else for(c=new _ds.KH,a=_ds.q(a.D),b=a.next();!b.done;b=a.next())_ds.MH(c,b.value)},HT=function(a,b){_ds.P(a,function d(){var e=this,f,k,l,m,n,p,r;return _ds.G(d,function(t){if(1==t.j)return f=
e,e.C?_ds.y(t,(0,_ds.ao)(),2):t.return();k=t.h;l=new _ds.KH;m=function(u){u=u.target;_ds.MH(l,u);f.D.delete(u);k.unregisterIntersectionForElement(u)};n=_ds.q(b);for(p=n.next();!p.done;p=n.next()){r=p.value;try{k.registerIntersectionForElement(r,m)}catch(u){m({target:r})}}_ds.z(t)})})},CT=function(a){var b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.Zh(a,"visually-hidden","",c))},JT=function(a,b){var c=
!1;if(a.m)for(var d=_ds.q(a.m.querySelectorAll("[menu]")),e=d.next();!e.done;e=d.next())e=e.value,e.getAttribute("menu")===b?(e.removeAttribute("hidden"),c=!0):_ds.Zh(a,"hidden","",e);return c},KT=function(a,b){b.defaultPrevented||(b=_ds.Ej(b.target,function(c){return c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a},!0),b!==a&&_ds.Th(b,_ds.rg(_ds.Gk(b.href).href)))},MT=function(a){return _ds.P(a,function c(){var d=this;return _ds.G(c,function(e){switch(e.j){case 1:if(!d.C)return e.return();
d.removeAttribute("user-scrolled");return _ds.y(e,_ds.Rk(),2);case 2:return _ds.y(e,LT(d),3);case 3:return _ds.y(e,d.V,4);case 4:return _ds.y(e,(0,_ds.ao)(),5);case 5:return _ds.y(e,_ds.Rk(),6);case 6:return _ds.y(e,LT(d),0)}})})},NT=function(a,b){(b=void 0===b?a:b)||(b=a);var c=_ds.q(b.querySelectorAll(".devsite-nav-active"));for(a=c.next();!a.done;a=c.next())a.value.classList.remove("devsite-nav-active");a=_ds.Wk(_ds.yk().pathname);a='[href="'+_ds.Gk(a).href+'"], [href="'+a+'"],\n        [alt-paths~="'+
a+'"]';b=_ds.q(b.querySelectorAll(a));for(a=b.next();!a.done;a=b.next())a.value.classList.add("devsite-nav-active")},OT=function(a,b){(b=void 0===b?a:b)||(b=a);var c=b.querySelector(".devsite-mobile-nav-bottom");if(c)for(var d=c.querySelector(".devsite-nav-active");d&&d.parentElement&&d.parentElement!==b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.Wl(a.eventHandler,d,"devsite-expandable-nav-transition-end",function(){d&&_ds.Zh(a,"animatable","",d)}),d.removeAttribute("collapsed")),
d=d.parentElement},LT=function(a){return _ds.P(a,function c(){var d=this,e;return _ds.G(c,function(f){if(1==f.j)return d.C&&d.m?_ds.y(f,(0,_ds.ao)(),2):f.return();e=d.m.querySelector(".devsite-nav-active");return!e||d.hasAttribute("user-scrolled")?f.F(0):_ds.y(f,PT(d,e),0)})})},PT=function(a,b){return _ds.P(a,function d(){var e=this,f,k;return _ds.G(d,function(l){if(1==l.j){if(!e.C)return l.return();f=e.hasAttribute("user-scrolled");k=_ds.sm(b,e,!0);e.scrollTop=k.y;return _ds.y(l,_ds.Rk(),2)}f&&_ds.Zh(e,
"user-scrolled","");_ds.z(l)})})},QT=function(a){return _ds.P(a,function c(){var d,e=this,f,k,l;return _ds.G(c,function(m){if(1==m.j)return _ds.y(m,(0,_ds.ao)(),2);d=m.h;f=_ds.q(e.D);for(k=f.next();!k.done;k=f.next())l=k.value,d.unregisterIntersectionForElement(l);_ds.z(m)})})},ST=function(a){_ds.P(a,function c(){var d=this,e,f,k;return _ds.G(c,function(l){if(1==l.j)return e=d,k=(f=document.documentElement.scrollHeight-document.documentElement.clientHeight)?document.documentElement.scrollTop/f:0,
_ds.Wl(d.eventHandler,d,_ds.IM,function(){e.removeAttribute("animatable")}),_ds.Zh(d,"animatable",""),d.hasAttribute("collapsed")?(_ds.Zh(d,"aria-expanded","true",d.h),_ds.Zh(d,"aria-label","Hide side navigation",d.h),_ds.Zh(d,"data-title","Hide side navigation",d.h),d.removeAttribute("collapsed"),RT(d,"Expanded book nav")):(d.h.removeAttribute("aria-expanded"),_ds.Zh(d,"aria-label","Show side navigation",d.h),_ds.Zh(d,"data-title","Show side navigation",d.h),_ds.Zh(d,"collapsed",""),RT(d,"Collapsed book nav")),
_ds.y(l,_ds.Rk(),2);f=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(k*f);_ds.z(l)})})},RT=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))};var TT=_ds.sa(["animatable"]),UT=_ds.sa(["aria-expanded"]),VT=_ds.sa(["aria-label"]),WT=_ds.sa(["collapsed"]),XT=_ds.sa(["data-title"]),ZT=_ds.sa(["fixed"]),$T=_ds.sa(["has-book-nav"]),aU=_ds.sa(["hidden"]),bU=_ds.sa(["role"]),cU=_ds.sa(["top-level-nav"]),dU=_ds.sa(["user-scrolled"]),eU=_ds.sa(["visually-hidden"]),fU="onpointerover"in window?"pointerover":"mouseover";_ds.w(DT,_ds.Yh);_ds.g=DT.prototype;
_ds.g.connectedCallback=function(){var a,b;return _ds.P(this,function d(){var e=this,f;return _ds.G(d,function(k){if(1==k.j)return e.C=!0,e.ic(e.j(TT),e.j(UT),e.j(VT),e.j(WT),e.j(XT),e.j(ZT),e.j($T),e.j(aU),e.j(bU),e.j(cU),e.j(dU),e.j(eU)),_ds.Zh(e,"role","menu"),_ds.bj(e.background,e),e.hasAttribute("hidden")&&(_ds.Zh(e,"hidden","",e.h),_ds.Zh(e,"hidden","",e.H)),_ds.y(k,(0,_ds.ao)(),2);if(3!=k.j)return f=k.h,e.W=f.hasFlagAccess(150),e.W&&(null===(a=e.parentElement)||void 0===a?void 0:a.insertBefore(e.h,
e.nextSibling),_ds.Zh(e,"aria-label","Hide side navigation",e.h),_ds.Zh(e,"data-title","Hide side navigation",e.h),_ds.Zh(e,"aria-expanded","true",e.h),null===(b=e.parentElement)||void 0===b?void 0:b.insertBefore(e.H,e.nextSibling)),e.L=f.hasFlagAccess(155),e.L&&(e.J=e.querySelector(".devsite-book-nav-filter"),e.J&&(e.v=e.J.querySelector("input[type=text]"),e.G=e.J.querySelector(".filter-clear-button"),ET(e))),CT(e),e.Z(),_ds.y(k,e.init(),3);IT(e);_ds.z(k)})})};
_ds.g.disconnectedCallback=function(){this.C=!1;_ds.Yl(this.eventHandler);QT(this);this.D.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.Zh(this,"visually-hidden","",a);a=_ds.q([this.background,this.h,this.H]);for(var b=a.next();!b.done;b=a.next())(b=b.value)&&_ds.ej(b);this.removeAttribute("animatable");document.body.style.removeProperty("--devsite-js-book-nav-scrollbar-width")};
_ds.g.attributeChangedCallback=function(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.Zh(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);for(var c=_ds.q([this.background,
this.h,this.H]),d=c.next();!d.done;d=c.next())(d=d.value)&&(b?_ds.Zh(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.N()};
_ds.g.Z=function(){var a=this;this.eventHandler.listen(this,"click",function(b){var c;if(!b.defaultPrevented){var d=b.target;"devsite-close-nav"===d.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.Zh(a,"top-level-nav",""));if(d.hasAttribute("menu")){var e=d.getAttribute("menu");e&&JT(a,e)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(d.classList.contains("devsite-nav-toggle")||
d.classList.contains("devsite-nav-title-no-path")||(null===(c=d.parentElement)||void 0===c?0:c.classList.contains("devsite-nav-title-no-path")))){a.m&&(b=a.m.querySelector("[menu=_book]"))&&b.contains(d)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}));var f;d instanceof Element&&d.matches("a.devsite-nav-title")?f=d:f=_ds.Fj(d,"a","devsite-nav-title");f&&!f.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});
this.eventHandler.listen(this,[fU,"focusin"],function(b){return void KT(a,b)});this.eventHandler.listen(document.body,"devsite-sitemask-hidden",function(){a.m&&(JT(a,"_book")?a.removeAttribute("top-level-nav"):_ds.Zh(a,"top-level-nav",""))});this.eventHandler.listen(document.body,"devsite-page-loaded",function(){return void a.M.Ea()});this.eventHandler.listen(this,"devsite-content-updated",function(){a.M.Ea()});this.eventHandler.listen(this,"scroll",function(){_ds.Zh(a,"user-scrolled","")});this.eventHandler.listen(this.h,
"click",function(){ST(a)});this.v&&this.K.length&&this.eventHandler.listen(this.v,"keyup",function(){var b,c,d,e,f,k;FT(a);GT(a);var l=null===(c=null===(b=a.v)||void 0===b?void 0:b.value)||void 0===c?void 0:c.trim().toLowerCase();if(l)for(null===(d=a.G)||void 0===d?void 0:d.classList.remove("hidden"),b=_ds.q(a.K),c=b.next();!c.done;c=b.next()){c=c.value;var m=c.querySelectorAll(".devsite-nav-text"),n=c.classList.contains("devsite-nav-expandable");var p=d=!1;if(l&&n&&(null===(f=null===(e=c.querySelector(".devsite-nav-text"))||
void 0===e?void 0:e.textContent)||void 0===f?0:f.toLowerCase().includes(l)))p=d=!0;else for(m=_ds.q(m),n=m.next();!n.done;n=m.next())n=n.value,l&&(null===(k=n.textContent)||void 0===k?0:k.toLowerCase().includes(l))&&(d=!0);if(!0===d){c.classList.remove("hidden");if(p)for(d=Array.from(c.querySelectorAll(".devsite-nav-item")),d=_ds.q(d),p=d.next();!p.done;p=d.next())p.value.classList.remove("hidden");d=void 0;(c=c.querySelector(".devsite-nav-text"))&&(p=null===(d=c.textContent)||void 0===d?void 0:d.replace(new RegExp("("+
l+")","ig"),"<mark>$1</mark>"))&&_ds.Km.kd(c,_ds.yg.h(p))}}else null===(p=a.G)||void 0===p?void 0:p.classList.add("hidden")});this.G&&this.eventHandler.listen(this.G,"click",function(){var b;a.v&&(a.v.value="");null===(b=a.G)||void 0===b?void 0:b.classList.add("hidden");FT(a);GT(a)})};
_ds.g.init=function(a){a=void 0===a?!0:a;return _ds.P(this,function c(){var d=this,e,f,k;return _ds.G(c,function(l){if(1==l.j){if(!d.C)return l.return();document.body.style.setProperty("--devsite-js-book-nav-scrollbar-width",d.offsetWidth-d.clientWidth+"px");d.m=d.querySelector(".devsite-mobile-nav-bottom");_ds.Zh(d,"top-level-nav","");d.m&&d.m.querySelector("[menu=_book]")&&d.removeAttribute("top-level-nav");0===d.children.length&&_ds.Zh(d,"hidden","");if(d.background)for(e=_ds.q(["hidden","fixed",
"animatable"]),f=e.next();!f.done;f=e.next())k=f.value,d.hasAttribute(k)&&_ds.Zh(d,k,"",d.background);return!d.hasAttribute("hidden")&&a?(NT(d),OT(d),_ds.y(l,MT(d),0)):_ds.y(l,_ds.Rk(),4)}return _ds.y(l,LT(d),0)})})};
_ds.g.eb=function(a){var b;return _ds.P(this,function d(){var e=this,f;return _ds.G(d,function(k){switch(k.j){case 1:if(!a){_ds.aj(e);k.F(2);break}f=a.querySelector("nav")||null;NT(e,f);OT(e,f);if(!f){k.F(3);break}return _ds.y(k,QT(e),4);case 4:e.D.clear(),IT(e,f,!1);case 3:_ds.$h(e,e.querySelector("nav"),f);case 2:return e.L&&(ET(e),e.v&&(e.v.value="",null===(b=e.G)||void 0===b?void 0:b.classList.add("hidden"))),_ds.y(k,_ds.Rk(),5);case 5:return _ds.y(k,e.init(!1),0)}})})};
_ds.ja.Object.defineProperties(DT,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["collapsed","fixed","hidden"]}}});DT.prototype.updateContent=DT.prototype.eb;DT.prototype.attributeChangedCallback=DT.prototype.attributeChangedCallback;DT.prototype.disconnectedCallback=DT.prototype.disconnectedCallback;DT.prototype.connectedCallback=DT.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",DT)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
