(function(_ds){var window=this;'use strict';var UW=function(){var a=void 0===a?_ds.IO.length:a;return _ds.IO.slice(0,a)},VW=function(a){var b=a.projectName,c=a.Ns,d=a.Os,e=a.zq,f=a.gq,k=a.It;a='<devsite-dialog class="devsite-feedback"><div class="devsite-dialog-contents"><h3 class="no-link">Send feedback about...</h3><div class="devsite-feedback-items"><a href="#" class="devsite-feedback-item" feedback-type="documentation" data-label="Docs Feedback Image" track-type="feedback" track-name="feedbackDocIcon"><div class="devsite-feedback-item-icon-container devsite-feedback-item-icon-color"><div class="devsite-feedback-item-icon material-icons" aria-hidden="true">description</div></div><div>This page</div><div class="devsite-feedback-item-type">Documentation feedback</div></a>';
f||(c=d?'<div class="devsite-feedback-item-icon material-icons" aria-hidden="true">'+_ds.gE(d)+"</div>":c?'<img src="'+_ds.Y(_ds.LE(c))+'" loading="lazy" alt="">':"",a+="<a"+(e?' href="'+_ds.Y(_ds.JE(e))+'"':' href="#"')+' class="devsite-feedback-item" feedback-type="product" data-label="Product Feedback Image" track-type="feedback" track-name="feedbackProductIcon"><div class="devsite-feedback-item-icon-container '+(d?"devsite-feedback-item-icon-color devsite-theme-primary":"devsite-feedback-item-icon-img")+
'">'+c+"</div><div>"+_ds.gE(b)+'</div><div class="devsite-feedback-item-type">',a+="Product feedback</div></a>");a+='</div><div class="devsite-feedback-notice">We appreciate your feedback! Please note that we cannot respond.</div>';k&&(a+='<div class="devsite-feedback-support"><span class="devsite-feedback-support-icon material-icons" aria-hidden="true">help</span><span>',b='Need help? Visit our <a href="'+(_ds.Y(_ds.JE(k))+'">support page</a>.'),a=a+b+"</span></div>");return(0,_ds.U)(a+'<div class="devsite-feedback-buttons"><button class="button-white" tabindex="1" data-label="Cancel Feedback Button" track-type="feedback" track-name="cancelFeedbackButton" feedback-cancel>Close</button></div></div></devsite-dialog>')},
eX=function(){var a=_ds.Yh.call(this,["devsite-dialog"])||this;a.eventHandler=new _ds.Sl;a.h=null;a.m=!1;a.ic((0,_ds.Mg)(WW),(0,_ds.Mg)(XW),(0,_ds.Mg)(YW),(0,_ds.Mg)(ZW),(0,_ds.Mg)($W),(0,_ds.Mg)(aX),(0,_ds.Mg)(bX),(0,_ds.Mg)(cX),(0,_ds.Mg)(dX));return a},iX=function(a,b){_ds.P(a,function d(){var e=this,f,k,l,m,n,p,r,t,u;return _ds.G(d,function(v){if(1==v.j)return f=e,k=b.currentTarget,l=k.getAttribute("feedback-type"),m="#"===k.getAttribute("href"),n={pageUrl:_ds.yk().toString(),context:e.getAttribute("context"),
type:l},p=UW(),p.length&&(n.errorStack=p),e.hasAttribute("rating-type")&&(n.ratingType=e.getAttribute("rating-type")),e.hasAttribute("rating-category")&&(n.ratingCategory=e.getAttribute("rating-category")),_ds.y(v,(0,_ds.ao)(),2);r=v.h;t={productId:e.getAttribute("product-id"),locale:r.getLocale(),bucket:e.getAttribute("bucket"),productVersion:e.getAttribute("version"),callback:function(){return void fX()},onLoadCallback:function(){return void gX(f)}};u={action:"click",label:k.getAttribute("data-label"),
category:k.getAttribute("data-category")||"Site-Wide Custom Events"};hX(e,u);m&&(b.preventDefault(),b.stopPropagation(),_ds.vF(t,n));_ds.z(v)})})},gX=function(a){var b;null===(b=a.h)||void 0===b?void 0:b.removeAttribute("open");_ds.ej(a.h)},fX=function(){Array.from(document.querySelectorAll('script[src*="www.google.com/tools/feedback/"]')).forEach(function(a){return _ds.ej(a)})},hX=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:b,bubbles:!0}))};var WW=_ds.sa(["bucket"]),XW=_ds.sa(["context"]),YW=_ds.sa(["product-id"]),ZW=_ds.sa(["data-label"]),$W=_ds.sa(["track-metadata-position"]),aX=_ds.sa(["track-name"]),bX=_ds.sa(["track-type"]),cX=_ds.sa(["disable"]),dX=_ds.sa(["project-"]),jX=_ds.sa(["open"]);_ds.w(eX,_ds.Yh);
eX.prototype.connectedCallback=function(){if(!this.m){var a=this.querySelector(".google-feedback"),b=new Map([["data-b","bucket"],["data-context","context"],["data-p","product-id"]]),c=new Map([["data-label","Send Feedback Button"],["track-metadata-position","content"],["track-name","sendFeedbackLink"],["track-type","feedback"]]);if(a){b=_ds.q(b.entries());for(var d=b.next();!d.done;d=b.next()){var e=_ds.q(d.value);d=e.next().value;e=e.next().value;if(a.hasAttribute(d)){var f=a.getAttribute(d)||"";
_ds.Zh(this,e,f);a.removeAttribute(d)}}c=_ds.q(c.entries());for(b=c.next();!b.done;b=c.next())d=_ds.q(b.value),b=d.next().value,d=d.next().value,a.hasAttribute(b)?(d=a.getAttribute(b)||"",_ds.Zh(this,b,d),a.removeAttribute(b)):_ds.Zh(this,b,d);a.classList.remove("google-feedback")}!this.hasAttribute("project-name")&&(a=document.querySelector('meta[property="og:site_name"]'))&&(a=a.getAttribute("content")||"",_ds.Zh(this,"project-name",a));this.hasAttribute("project-icon")?_ds.Zh(this,"project-icon",
_ds.Gk(this.getAttribute("project-icon")||"").href||""):(a=document.querySelector('link[rel="apple-touch-icon"]'))&&_ds.Zh(this,"project-icon",a.getAttribute("href")||"");this.h=_ds.aF(VW,{gq:this.hasAttribute("disable-product-feedback"),zq:this.getAttribute("project-feedback-url"),Ns:this.getAttribute("project-icon"),Os:this.getAttribute("project-icon-name"),projectName:this.getAttribute("project-name")||"",It:this.getAttribute("project-support-url")});this.m=!0}this.Z()};
eX.prototype.disconnectedCallback=function(){_ds.Yl(this.eventHandler)};
eX.prototype.Z=function(){var a=this,b;this.eventHandler.listen(this,"click",function(e){if("A"===e.target.tagName||"BUTTON"===e.target.tagName)e.preventDefault(),e.stopPropagation(),a.h&&(document.body.appendChild(a.h),_ds.Km.Vb([(0,_ds.Mg)(jX)],a.h,"open",""),e={action:"click",category:a.getAttribute("data-category")||"Site-Wide Custom Events",label:a.getAttribute("data-label")},hX(a,e))});if(this.h){var c=Array.from(this.h.querySelectorAll("[feedback-type]"));c=_ds.q(c);for(var d=c.next();!d.done;d=
c.next())this.eventHandler.listen(d.value,"click",function(e){iX(a,e)});(c=null===(b=this.h)||void 0===b?void 0:b.querySelector("button[feedback-cancel]"))&&this.eventHandler.listen(c,"click",function(){gX(a);var e,f=null===(e=a.h)||void 0===e?void 0:e.querySelector("button[feedback-cancel]");e={action:"click",label:null===f||void 0===f?void 0:f.getAttribute("data-label"),category:(null===f||void 0===f?void 0:f.getAttribute("data-category"))||"Site-Wide Custom Events"};hX(a,e)});this.eventHandler.listen(this.h,
"devsite-dialog-hide",function(){_ds.ej(a.h)})}};eX.prototype.disconnectedCallback=eX.prototype.disconnectedCallback;eX.prototype.connectedCallback=eX.prototype.connectedCallback;try{window.customElements.define("devsite-feedback",eX)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteFeedback",a)};})(_ds_www);
