(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var H0=function(){var a=_ds.Yh.call(this)||this;a.m=_ds.Sm();a.h=new _ds.Sl;F0().then(function(){G0(a)});return a},G0=function(a){var b;return _ds.Ra(function(c){return(b=_ds.FN.get("django_language"))?_ds.y(c,a.m.set("language_preference",b),0):c.F(0)})},J0=function(a){_ds.Yl(a.h);var b=a.querySelector(".devsite-language-selector-select");b&&a.h.listen(b,"change",function(c){I0(a,c)})},I0=function(a,b){var c,d;_ds.Ra(function(e){switch(e.j){case 1:return _ds.y(e,DevsiteApp.whenReady(),
2);case 2:return _ds.FN.remove("django_language"),c=b.target,_ds.FN.set("django_language",c.value,{Jb:15552E3,path:"/"}),d=document.documentElement.getAttribute("lang"),_ds.y(e,K0(a,d,c.value),3);case 3:return _ds.y(e,G0(a),4);case 4:var f=_ds.rg(_ds.pk(new _ds.ak(_ds.Ui().location.href),"hl").toString());_ds.Ui().location.assign(_ds.Sh(f));_ds.z(e)}})},K0=function(a,b,c){var d,e;return _ds.Ra(function(f){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",
label:"Language Selector",action:b+" to "+c},bubbles:!0}));d={name:"change",type:"languageSelector",metadata:{"selected-language":c,"original-language":b}};e={eventData:JSON.stringify(d)};a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:e,bubbles:!0}));_ds.z(f)})},F0=function(){return _ds.Ra(function(a){if(1==a.j)return _ds.FN.get("django_language")?a.F(0):_ds.y(a,DevsiteApp.whenReady(),3);_ds.FN.set("django_language",DevsiteApp.getLocale()||"en",{Jb:15552E3,path:"/"});
_ds.z(a)})};_ds.w(H0,_ds.Yh);H0.prototype.connectedCallback=function(){J0(this)};H0.prototype.disconnectedCallback=function(){_ds.Yl(this.h)};H0.prototype.eb=function(a){a&&(_ds.$h(this,this.querySelector(".devsite-language-selector-menu"),a.querySelector(".devsite-language-selector-menu")),J0(this))};H0.prototype.updateContent=H0.prototype.eb;H0.prototype.disconnectedCallback=H0.prototype.disconnectedCallback;H0.prototype.connectedCallback=H0.prototype.connectedCallback;try{window.customElements.define("devsite-language-selector",H0)}catch(a){console.warn("devsite.app.customElement.DevsiteLanguageSelector",a)};})(_ds_www);
