(function(_ds){var window=this;'use strict';var ZU=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_ds.eb(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var k=0;k<f;k++)a[e+k]=d[k]}else a.push(d)}},$U=function(){var a=new _ds.FG;ZU(a.M,"data-devsite-credential-type data-modal-dialog-id data-scope data-terminal-prefix data-title data-type".split(" "));return a},aV=function(){var a=$U();["devsite-var"].forEach(function(b){this.L.push(b)},a);return a},bV=function(){var a='<div class="devsite-code-buttons-container" role="group" aria-label="'+
_ds.qE("Action buttons");return(0,_ds.U)(a+'"></div>')},cV=function(a){a=a.label;return(0,_ds.U)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.Y(a)+'" data-title="'+_ds.Y(a)+'"></button>')},dV=function(a){a=a.label;return(0,_ds.U)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+
_ds.Y(a)+'" data-title="'+_ds.Y(a)+'"></button>')},eV=function(a){var b=a.label;return(0,_ds.U)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+_ds.Y(a.Vp)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.Y(b)+'" data-title="'+_ds.Y(b)+'"></button>')},fV=function(a){a=a.label;return(0,_ds.U)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+
_ds.Y(a)+'" data-title="'+_ds.Y(a)+'"></button>')},gV=function(){var a=_ds.Yh.call(this,["devsite-snackbar"])||this;a.h=null;a.v=null;a.K="";a.D=null;a.m=new _ds.Sl;a.L=!1;a.C=null;a.G=null;a.M=new _ds.Zl;a.N=new _ds.JG(_ds.PG(aV()));a.H=null;a.J=new _ds.zn;return a},hV=function(a){Array.from(a.getElementsByClassName("prettyprint")).forEach(function(b){b.classList.remove("prettyprint");var c=(c=b.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?c[1]:void 0;c=window.prettyPrintOne(b.innerHTML,c);
_ds.Km.kd(b,a.N.h(c));b.getElementsByTagName("strong").length&&b.classList.add("devsite-code-highlight")})},iV=function(a){var b=a.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))a.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");a.setAttribute("data-copy-event-label",
b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");b=b.getAttribute("data-label");a.K=b?"Copy code sample: "+b:"Copy code sample"}var c=a.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample");c&&(a.setAttribute("js-fiddle",""),c.classList.remove("devsite-enable-open-in-jsfiddle"),c.classList.add("devsite-jsfiddle-code-sample"));a.hasAttribute("js-fiddle")&&c&&["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"].forEach(function(d){c.hasAttribute("data-"+
d)&&(a.setAttribute(d,c.getAttribute("data-"+d)),c.removeAttribute("data-"+d))})},jV=function(a){var b,c;return _ds.Ra(function(d){if(1==d.j){b=Array.from(a.querySelector("pre:not(.devsite-copy-hide)").childNodes);_ds.sJ(document.body,b);if(!a.H)return d.F(0);c=new _ds.Zl;a.v.setAttribute("aria-label","Code sample copied to clipboard");_ds.Wl(a.m,a.H,_ds.IM,function(){c.resolve()});return _ds.y(d,c.promise,3)}_ds.Wl(a.m,a.H,_ds.IM,function(){a.v.setAttribute("aria-label",a.K)});_ds.z(d)})},kV=function(a){a.D&&
a.m.listen(a.D,"click",function(){return void a.setAttribute("dark-code","")});a.G&&a.m.listen(a.G,"click",function(){return void a.removeAttribute("dark-code")});a.v&&a.m.listen(a.v,"click",function(){return void jV(a)});a.C&&a.m.listen(a.C,"click",function(){var b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.FJ(c,b):_ds.EJ([a],b)})};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(fa){return fa.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;")}function b(fa,X,na){switch(fa.nodeType){case 1:var za=fa.tagName.toLowerCase();X.push("<",za);var ka=fa.attributes,Ma=ka.length;if(Ma){if(na){for(var Za=[],qa=Ma;0<=--qa;)Za[qa]=ka[qa];Za.sort(function(Xa,mb){return Xa.name<mb.name?-1:Xa.name===mb.name?0:1});ka=Za}for(qa=0;qa<Ma;++qa)Za=ka[qa],Za.specified&&X.push(" ",Za.name.toLowerCase(),'="',Za.value.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;").replace(x,
"&quot;"),'"')}X.push(">");for(ka=fa.firstChild;ka;ka=ka.nextSibling)b(ka,X,na);!fa.firstChild&&/^(?:br|link|img)$/.test(za)||X.push("</",za,">");break;case 3:case 4:X.push(a(fa.nodeValue))}}function c(fa){function X(La){if("\\"!==La.charAt(0))return La.charCodeAt(0);switch(La.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(La.substring(2),16)||La.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(La.substring(1),
8);default:return La.charCodeAt(1)}}function na(La){if(32>La)return(16>La?"\\x0":"\\x")+La.toString(16);La=String.fromCharCode(La);if("\\"===La||"-"===La||"["===La||"]"===La)La="\\"+La;return La}function za(La){var ma=La.substring(1,La.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));La=[];for(var ba=[],pb="^"===ma[0],Ja=pb?1:0,jb=ma.length;Ja<jb;++Ja){var cb=ma[Ja];switch(cb){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":La.push(cb);
continue}cb=X(cb);if(Ja+2<jb&&"-"===ma[Ja+1]){var wb=X(ma[Ja+2]);Ja+=2}else wb=cb;ba.push([cb,wb]);65>wb||122<cb||(65>wb||90<cb||ba.push([Math.max(65,cb)|32,Math.min(wb,90)|32]),97>wb||122<cb||ba.push([Math.max(97,cb)&-33,Math.min(wb,122)&-33]))}ba.sort(function($a,gc){return $a[0]-gc[0]||gc[1]-$a[1]});ma=[];cb=[NaN,NaN];for(Ja=0;Ja<ba.length;++Ja)jb=ba[Ja],jb[0]<=cb[1]+1?cb[1]=Math.max(cb[1],jb[1]):ma.push(cb=jb);ba=["["];pb&&ba.push("^");ba.push.apply(ba,La);for(Ja=0;Ja<ma.length;++Ja)jb=ma[Ja],
ba.push(na(jb[0])),jb[1]>jb[0]&&(jb[1]+1>jb[0]&&ba.push("-"),ba.push(na(jb[1])));ba.push("]");return ba.join("")}function ka(La){for(var ma=La.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),ba=ma.length,pb=[],Ja=0,jb=0;Ja<ba;++Ja){var cb=ma[Ja];"("===cb?++jb:"\\"===cb.charAt(0)&&(cb=+cb.substring(1))&&cb<=jb&&(pb[cb]=-1)}for(Ja=1;Ja<pb.length;++Ja)-1===pb[Ja]&&(pb[Ja]=
++Ma);for(jb=Ja=0;Ja<ba;++Ja)cb=ma[Ja],"("===cb?(++jb,void 0===pb[jb]&&(ma[Ja]="(?:")):"\\"===cb.charAt(0)&&(cb=+cb.substring(1))&&cb<=jb&&(ma[Ja]="\\"+pb[jb]);for(jb=Ja=0;Ja<ba;++Ja)"^"===ma[Ja]&&"^"!==ma[Ja+1]&&(ma[Ja]="");if(La.ignoreCase&&Za)for(Ja=0;Ja<ba;++Ja)cb=ma[Ja],La=cb.charAt(0),2<=cb.length&&"["===La?ma[Ja]=za(cb):"\\"!==La&&(ma[Ja]=cb.replace(/[a-zA-Z]/g,function(wb){wb=wb.charCodeAt(0);return"["+String.fromCharCode(wb&-33,wb|32)+"]"}));return ma.join("")}for(var Ma=0,Za=!1,qa=!1,Xa=
0,mb=fa.length;Xa<mb;++Xa){var nb=fa[Xa];if(nb.ignoreCase)qa=!0;else if(/[a-z]/i.test(nb.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){Za=!0;qa=!1;break}}var kb=[];Xa=0;for(mb=fa.length;Xa<mb;++Xa){nb=fa[Xa];if(nb.global||nb.multiline)throw Error(""+nb);kb.push("(?:"+ka(nb)+")")}return new RegExp(kb.join("|"),qa?"gi":"g")}function d(fa){var X=0;return function(na){for(var za=null,ka=0,Ma=0,Za=na.length;Ma<Za;++Ma)switch(na.charAt(Ma)){case "\t":za||(za=[]);za.push(na.substring(ka,
Ma));ka=fa-X%fa;for(X+=ka;0<=ka;ka-=16)za.push("                ".substring(0,ka));ka=Ma+1;break;case "\n":X=0;break;default:++X}if(!za)return na;za.push(na.substring(ka));return za.join("")}}function e(fa,X,na,za){X&&(fa={source:X,jk:fa},na(fa),za.push.apply(za,fa.Gk))}function f(fa,X){function na(Za){for(var qa=Za.jk,Xa=[qa,"pln"],mb=0,nb=Za.source.match(ka)||[],kb={},La=0,ma=nb.length;La<ma;++La){var ba=nb[La],pb=kb[ba],Ja=void 0;if("string"===typeof pb)var jb=!1;else{var cb=za[ba.charAt(0)];if(cb)Ja=
ba.match(cb[1]),pb=cb[0];else{for(jb=0;jb<Ma;++jb)if(cb=X[jb],Ja=ba.match(cb[1])){pb=cb[0];break}Ja||(pb="pln")}!(jb=5<=pb.length&&"lang-"===pb.substring(0,5))||Ja&&"string"===typeof Ja[1]||(jb=!1,pb="src");jb||(kb[ba]=pb)}cb=mb;mb+=ba.length;if(jb){jb=Ja[1];var wb=ba.indexOf(jb),$a=wb+jb.length;Ja[2]&&($a=ba.length-Ja[2].length,wb=$a-jb.length);pb=pb.substring(5);e(qa+cb,ba.substring(0,wb),na,Xa);e(qa+cb+wb,jb,n(pb,jb),Xa);e(qa+cb+$a,ba.substring($a),na,Xa)}else Xa.push(qa+cb,pb)}Za.Gk=Xa}var za=
{},ka;(function(){for(var Za=fa.concat(X),qa=[],Xa={},mb=0,nb=Za.length;mb<nb;++mb){var kb=Za[mb],La=kb[3];if(La)for(var ma=La.length;0<=--ma;)za[La.charAt(ma)]=kb;kb=kb[1];La=""+kb;Xa.hasOwnProperty(La)||(qa.push(kb),Xa[La]=null)}qa.push(/[\0-\uffff]/);ka=c(qa)})();var Ma=X.length;return na}function k(fa){var X=[],na=[];fa.tripleQuotedStrings?X.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,
null,"'\""]):fa.multiLineStrings?X.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):X.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);fa.verbatimStrings&&na.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var za=fa.hashComments;za&&(fa.cStyleComments?(1<za?X.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):X.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),na.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):X.push(["com",/^#[^\r\n]*/,null,"#"]));fa.cStyleComments&&(na.push(["com",/^\/\/[^\r\n]*/,null]),na.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));fa.regexLiterals&&na.push(["lang-regex",new RegExp("^"+r+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);fa=fa.keywords.replace(/^\s+|\s+$/g,"");fa.length&&na.push(["kwd",new RegExp("^(?:"+fa.replace(/\s+/g,
"|")+")\\b"),null]);X.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);na.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(X,na)}function l(fa){function X(rc){if(rc>Xa){mb&&mb!==nb&&(qa.push("</span>"),mb=null);!mb&&nb&&(mb=nb,qa.push('<span class="',mb,'">'));var be=
a(ma(na.substring(Xa,rc))).replace(cb?pb:ba,"$1&#160;");cb=jb.test(be);qa.push(be.replace(Ja,Od));Xa=rc}}var na=fa.source,za=fa.xq,ka=fa.Gk,Ma=fa.Tl,Za=fa.Lm,qa=[],Xa=0,mb=null,nb=null,kb=0,La=0,ma=d(window.PR_TAB_WIDTH),ba=/([\r\n ]) /g,pb=/(^| ) /gm,Ja=/\r\n?|\n/g,jb=/[ \r\n]$/,cb=!0,wb=window._pr_isIE6();Za=wb?Za&&"PRE"===Za.tagName?6===wb?"&#160;\r\n":7===wb?"&#160;<br />\r":8===wb?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(Ma){var $a=[];for(wb=0;10>wb;++wb)$a[wb]=Za+'</li><li class="L'+
wb+'">';var gc="number"===typeof Ma?Ma-1:0;qa.push('<ol class="linenums"><li class="L',gc%10,'"');gc&&qa.push(' value="',gc+1,'"');qa.push(">");var Od=function(){var rc=$a[++gc%10];return mb?"</span>"+rc+'<span class="'+mb+'">':rc}}else Od=Za;for(;;)if(kb<za.length&&(La<ka.length?za[kb]<=ka[La]:1))X(za[kb]),mb&&(qa.push("</span>"),mb=null),qa.push(za[kb+1]),kb+=2;else if(La<ka.length)X(ka[La]),nb=ka[La+1],La+=2;else break;X(na.length);mb&&qa.push("</span>");Ma&&qa.push("</li></ol>");fa.Ji=qa.join("")}
function m(fa,X){for(var na=X.length;0<=--na;){var za=X[na];xa.hasOwnProperty(za)?"console"in window&&console.warn("cannot override language handler %s",za):xa[za]=fa}}function n(fa,X){fa&&xa.hasOwnProperty(fa)||(fa=/^\s*</.test(X)?"default-markup":"default-code");return xa[fa]}function p(fa){var X=fa.Km,na=fa.Jl;fa.Ji=X;try{var za=X.match(Z);X=[];var ka=0,Ma=[];if(za)for(var Za=0,qa=za.length;Za<qa;++Za){var Xa=za[Za];if(1<Xa.length&&"<"===Xa.charAt(0)){if(!V.test(Xa))if(la.test(Xa))X.push(Xa.substring(9,
Xa.length-3)),ka+=Xa.length-12;else if(ua.test(Xa))X.push("\n"),++ka;else if(0<=Xa.indexOf("nocode")&&Xa.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var mb=Xa.match(Ca)[2],nb=1;var kb=Za+1;a:for(;kb<qa;++kb){var La=za[kb].match(Ca);if(La&&La[2]===mb)if("/"===La[1]){if(0===--nb)break a}else++nb}kb<qa?(Ma.push(ka,za.slice(Za,kb+1).join("")),Za=kb):Ma.push(ka,Xa)}else Ma.push(ka,Xa)}else{nb=Xa;var ma=nb.indexOf("&");if(0>ma)var ba=
nb;else{for(--ma;0<=(ma=nb.indexOf("&#",ma+1));){var pb=nb.indexOf(";",ma);if(0<=pb){var Ja=nb.substring(ma+3,pb),jb=10;Ja&&"x"===Ja.charAt(0)&&(Ja=Ja.substring(1),jb=16);var cb=parseInt(Ja,jb);isNaN(cb)||(nb=nb.substring(0,ma)+String.fromCharCode(cb)+nb.substring(pb+1))}}ba=nb.replace(B,"<").replace(D,">").replace(C,"'").replace(O,'"').replace(S," ").replace(W,"&")}X.push(ba);ka+=ba.length}}var wb=X.join("");fa.source=wb;fa.jk=0;fa.xq=Ma;n(na,wb)(fa);l(fa)}catch($a){"console"in window&&console.log($a&&
$a.stack?$a.stack:$a)}}var r=function(){for(var fa="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),X="(?:^^|[+-]",na=0;na<fa.length;++na)X+="|"+fa[na].replace(/([^=<>:&a-z])/g,"\\$1");return X+")\\s*"}(),t=/&/g,u=/</g,v=/>/g,x=/"/g,B=/&lt;/g,D=/&gt;/g,C=/&apos;/g,O=/&quot;/g,W=/&amp;/g,S=/&nbsp;/g,da=/[\r\n]/g,T=null,Z=RegExp("[^<]+|\x3c!--[\\s\\S]*?--\x3e|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|</?[a-zA-Z](?:[^>\"']|'[^']*'|\"[^\"]*\")*>|<",
"g"),V=/^\x3c!--/,la=/^<!\[CDATA\[/,ua=/^<br\b/i,Ca=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,ia=k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),xa={};m(ia,["default-code"]);m(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));m(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);m(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);m(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));m(k({keywords:"null true false"}),["json"]);m(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);m(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);m(k({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);m(k({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);m(k({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);m(k({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);m(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);m(k({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);m(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(fa,X,na){fa={Km:fa,Jl:X,Tl:na};p(fa);return fa.Ji};window.prettyPrint=function(fa){function X(){for(var nb=
window.PR_SHOULD_USE_CONTINUATION?qa.now()+250:Infinity;Xa<za.length&&qa.now()<nb;Xa++){var kb=za[Xa];if(kb.className&&0<=kb.className.indexOf("prettyprint")){var La=kb.className.match(/\blang-(\w+)\b/);La&&(La=La[1]);for(var ma=!1,ba=kb.parentNode;ba;ba=ba.parentNode)if(("pre"===ba.tagName||"code"===ba.tagName||"xmp"===ba.tagName)&&ba.className&&0<=ba.className.indexOf("prettyprint")){ma=!0;break}if(!ma){ba=kb;null===T&&(ma=document.createElement("PRE"),ma.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
T=!/</.test(ma.innerHTML));if(T)if(ma=ba.innerHTML,"XMP"===ba.tagName)ma=a(ma);else{if("PRE"!==ba.tagName&&da.test(ma)){var pb="";ba.currentStyle?pb=ba.currentStyle.whiteSpace:window.getComputedStyle&&(pb=window.getComputedStyle(ba,null).whiteSpace);ba=!pb||"pre"===pb}else ba=!0;ba||(ma=ma.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{ma=[];for(ba=ba.firstChild;ba;ba=ba.nextSibling)b(ba,ma);ma=ma.join("")}ma=ma.replace(/(?:\r\n?|\n)$/,"");ba=kb.className.match(/\blinenums\b(?::(\d+))?/);
mb={Km:ma,Jl:La,Lm:kb,Tl:ba?ba[1]&&ba[1].length?+ba[1]:!0:!1};p(mb);if(kb=mb.Ji)if(La=mb.Lm,"XMP"===La.tagName){ma=document.createElement("PRE");for(ba=0;ba<La.attributes.length;++ba)pb=La.attributes[ba],pb.specified&&("class"===pb.name.toLowerCase()?ma.className=pb.value:ma.setAttribute(pb.name,pb.value));ma.innerHTML=kb;La.parentNode.replaceChild(ma,La)}else La.innerHTML=kb}}}Xa<za.length?setTimeout(X,250):fa&&fa()}for(var na=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),
document.getElementsByTagName("xmp")],za=[],ka=0;ka<na.length;++ka)for(var Ma=0,Za=na[ka].length;Ma<Za;++Ma)za.push(na[ka][Ma]);na=null;var qa=Date;qa.now||(qa={now:function(){return(new Date).getTime()}});var Xa=0,mb;X()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:m,sourceDecorator:k,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",
PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],[PR.PR_LITERAL,
/^(?:true|false|null)\b/],[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);_ds.w(gV,_ds.Yh);gV.prototype.whenReady=function(){return this.M.promise};
gV.prototype.connectedCallback=function(){var a=this,b;return _ds.Ra(function(c){switch(c.j){case 1:return _ds.y(c,DevsiteApp.whenReady(),2);case 2:return a.L||(iV(a),hV(a),a.L=!0),a.J.get("pref_dark-code")&&a.setAttribute("dark-code",""),a.M.resolve(),_ds.A(c,3),_ds.y(c,DevsiteApp.intersectionEnterForElement(a),5);case 5:_ds.E(c,4);break;case 3:if(b=_ds.F(c),"IntersectionObserver not supported"!==b.message)return c.return();case 4:var d=a.querySelector(".devsite-code-buttons-container");if(d)a.h=
d;else{a.h=_ds.aF(bV);a.hasAttribute("scope")&&(a.C=_ds.aF(fV,{label:"Open code sample in JSFiddle"}),(a.hasAttribute("jsfiddle-label")||a.hasAttribute("jsfiddle-title"))&&a.C.setAttribute("data-label",a.getAttribute("jsfiddle-label")||a.getAttribute("jsfiddle-title")),a.h.appendChild(a.C));a.D=_ds.aF(cV,{label:"Dark code theme"});a.h.appendChild(a.D);a.G=_ds.aF(dV,{label:"Light code theme"});a.h.appendChild(a.G);if(!a.hasAttribute("no-copy")){d=a.getAttribute("data-copy-event-label");var e="Click To Copy";
d&&(e+=": "+d);a.v=_ds.aF(eV,{label:a.K,Vp:e});a.h.appendChild(a.v)}a.prepend(a.h)}kV(a);a.H=document.querySelector("devsite-snackbar");_ds.z(c)}})};gV.prototype.disconnectedCallback=function(){var a=this;return _ds.Ra(function(b){if(1==b.j)return _ds.y(b,DevsiteApp.whenReady(),2);DevsiteApp.unregisterIntersectionForElement(a);a.h&&a.removeChild(a.h);_ds.Yl(a.m);_ds.z(b)})};
gV.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.Ra(function(e){if(1==e.j){if("dark-code"!==a||b===c)return e.F(0);if(d.hasAttribute("dark-code"))return d.J.set("pref_dark-code","1"),_ds.y(e,_ds.Rk(),6);d.J.remove("pref_dark-code");return _ds.y(e,_ds.Rk(),5)}if(6!=e.j)return Array.from(document.querySelectorAll("devsite-code[dark-code]")).forEach(function(f){f.removeAttribute("dark-code")}),e.F(0);Array.from(document.querySelectorAll("devsite-code:not([dark-code])")).filter(function(f){return f!==
d}).forEach(function(f){f.setAttribute("dark-code","")});_ds.z(e)})};_ds.ja.Object.defineProperties(gV,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dark-code"]}}});gV.prototype.attributeChangedCallback=gV.prototype.attributeChangedCallback;gV.prototype.disconnectedCallback=gV.prototype.disconnectedCallback;gV.prototype.connectedCallback=gV.prototype.connectedCallback;gV.prototype.whenReady=gV.prototype.whenReady;try{window.customElements.define("devsite-code",gV)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
