(function(_ds){var window=this;'use strict';var rT=function(){_ds.hu.apply(this,arguments);this.v=null},sT=function(a){return _ds.P(a,function c(){var d=this,e;return _ds.G(c,function(f){if(1==f.j)return _ds.y(f,_ds.ju(d),2);if(3!=f.j)return d.v?f.return(d.v):_ds.y(f,d.getConfig(),3);e=f.h;d.v=new _ds.Jr(e);return f.return(d.v)})})},tT=function(a){var b=a.Ua;a=a.zb;return(0,_ds.U)('<div class="devsite-badger-award-inner"><devsite-badge-awarded badge-name="'+_ds.Y(b.title)+'" badge-icon-url="'+_ds.Y(_ds.JE(b.imageUrl))+'" badge-url="'+
_ds.Y(_ds.JE(b.url))+'"'+(null!=b.currentTierCount?' badge-count="'+_ds.Y(b.currentTierCount)+'"':"")+(null!=b.complete?' badge-complete="'+_ds.Y(b.complete)+'"':"")+(null!=b.isNewTier?' is-new-tier="'+_ds.Y(b.isNewTier)+'"':"")+(b.path?' badge-path="'+_ds.Y(b.path)+'"':"")+(b.shareTitle?' badge-share-title="'+_ds.Y(b.shareTitle)+'"':"")+(b.shareDescription?' badge-share-description="'+_ds.Y(b.shareDescription)+'"':"")+(b.nextPlaylistUrl?' next-playlist-url="'+_ds.Y(_ds.JE(b.nextPlaylistUrl))+'"':
"")+(b.redeemAnotherBtn?" redeem-another":"")+(b.hideButtons?" hide-buttons":"")+(b.redeemCode?' redeem-code="'+_ds.Y(b.redeemCode)+'"':"")+(a?' return-uri="'+_ds.Y(_ds.JE(a))+'"':"")+" dismiss></devsite-badge-awarded></div>")},uT=function(){return(0,_ds.U)('<div class="devsite-badger-award"></div>')},vT=function(){var a=_ds.JH.call(this,["devsite-badge-awarded"])||this;a.eventHandler=new _ds.Sl(a);a.m=new _ds.zn;a.h=null;a.fb=[];a.v=!1;return a},wT=function(a){return _ds.P(a,function c(){var d=this,
e,f,k,l;return _ds.G(c,function(m){if(1==m.j){if(!d.h)return m.return();e=d.h.querySelectorAll(".devsite-badger-award-inner");f=e[0];if(!f)return m.F(0);k=f.querySelector("devsite-badge-awarded");if(null===k||void 0===k?0:k.Ri)null===k||void 0===k?void 0:k.Ri();l=null===k||void 0===k?void 0:k.getAttribute("badge-path");d.fb=d.fb.filter(function(n){return n.path!==l});f.removeAttribute("show");return _ds.y(m,_ds.Vk(200),3)}_ds.ej(f);1===e.length&&(_ds.ej(d.h),d.h=null);_ds.z(m)})})},yT=function(a){if(_ds.yn(a.m)){var b=
_ds.AH();if(b){b=b.filter(function(f){return 3>f.displayCount});0<b.length?a.m.set("temp_badges",JSON.stringify(b)):a.m.remove("temp_badges");b=_ds.q(b);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=new URL(c.awardedBy,document.location.origin),e=_ds.yk();(!c.awardedBy||d.origin===e.origin&&d.pathname===e.pathname)&&c.complete&&xT(a,c)}}}},xT=function(a,b){var c;_ds.P(a,function e(){var f=this,k,l,m,n,p;return _ds.G(e,function(r){switch(r.j){case 1:k=f;if(!b||!b.complete||f.fb.find(function(t){return t.path===
b.path})||"error"===document.body.getAttribute("type")||zT.exec(document.location.pathname))return r.return();f.fb.push(b);f.h||((l=document.querySelector(".static-badge-awarded-container"))?(f.h=l,f.v=!0):(f.h=_ds.aF(uT),document.body.appendChild(f.h)));_ds.A(r,2);return _ds.y(r,window.customElements.whenDefined("devsite-badge-awarded"),4);case 4:_ds.E(r,3);break;case 2:_ds.F(r);case 3:m=null===(c=_ds.Jk())||void 0===c?void 0:c.href;n=_ds.aF(tT,{Ua:b,zb:m});if(!n)return r.return();f.eventHandler.listen(n,
"devsite-badge-awarded-dismissed",function(){wT(k)});if(p=n.querySelector("devsite-badge-awarded"))f.h.appendChild(n),_ds.Wl(f.eventHandler,p,"running",function(){null===n||void 0===n?void 0:n.setAttribute("show","");var t,u,v=null===(t=k.h)||void 0===t?void 0:t.querySelectorAll("devsite-badge-awarded");if(v&&!k.v)for(t=0;t<v.length;t++)null===(u=v[t])||void 0===u?void 0:u.dispatchEvent(new CustomEvent("devsite-badge-awarded-stack-num-changed",{bubbles:!0,detail:{Pr:v.length-1-t}}))});_ds.z(r)}})})};
_ds.w(rT,_ds.hu);_ds.g=rT.prototype;_ds.g.vc=function(){return _ds.P(this,function b(){var c=this,d;return _ds.G(b,function(e){if(1==e.j)return _ds.y(e,sT(c),2);d=e.h;return e.return(d.vc())})})};
_ds.g.ad=function(a){a=void 0===a?!1:a;return _ds.P(this,function c(){var d=this,e,f,k,l,m;return _ds.G(c,function(n){switch(n.j){case 1:return _ds.y(n,sT(d),2);case 2:return e=n.h,f=_ds.qu(d,"getWalletId",a),k=_ds.ru(d,f),k||(k=e.ad(a),_ds.tu(d,f,k)),l=null,_ds.A(n,3,4),_ds.y(n,k,6);case 6:l=n.h;case 4:_ds.Fa(n);_ds.su(d,f);_ds.Ga(n,5);break;case 3:throw m=_ds.F(n),m;case 5:return n.return(l)}})})};
_ds.g.Ed=function(){return _ds.P(this,function b(){var c=this,d;return _ds.G(b,function(e){if(1==e.j)return _ds.y(e,sT(c),2);d=e.h;return e.return(d.Ed())})})};_ds.g.Jd=function(){return _ds.P(this,function b(){var c=this,d,e,f,k;return _ds.G(b,function(l){switch(l.j){case 1:return _ds.y(l,sT(c),2);case 2:return d=l.h,e=_ds.qu(c,"syncWallet"),f=_ds.ru(c,e),f||(f=d.Jd(),_ds.tu(c,e,f)),_ds.A(l,3,4),_ds.y(l,f,4);case 4:_ds.Fa(l);_ds.su(c,e);_ds.Ga(l,0);break;case 3:throw k=_ds.F(l),k;}})})};
_ds.g.je=function(){return _ds.P(this,function b(){var c=this,d;return _ds.G(b,function(e){if(1==e.j)return _ds.y(e,sT(c),2);d=e.h;d.je();_ds.z(e)})})};var zT=/\/redeem.*|\/u[\/]?.*|\/settings[\/]?.*?/;_ds.w(vT,_ds.JH);vT.prototype.connectedCallback=function(){this.Z()};vT.prototype.disconnectedCallback=function(){_ds.Yl(this.eventHandler);wT(this)};
vT.prototype.Jd=function(){return _ds.P(this,function b(){var c,d,e,f,k;return _ds.G(b,function(l){switch(l.j){case 1:return _ds.y(l,(0,_ds.ao)(),2);case 2:return _ds.y(l,window.customElements.whenDefined("devsite-user"),3);case 3:c=document.querySelector("devsite-user#devsite-user");if(!c)return l.return();d=!1;_ds.A(l,4);return _ds.y(l,c.isSignedIn(),6);case 6:d=l.h;_ds.E(l,5);break;case 4:_ds.F(l);case 5:if(!d)return l.return();e=new rT;return _ds.y(l,e.vc(),7);case 7:f=l.h;if(!f)return l.return();
k=new _ds.Eu;_ds.A(l,8);return _ds.y(l,k.Y(),10);case 10:_ds.E(l,0);break;case 8:_ds.F(l),_ds.z(l)}})})};vT.prototype.Z=function(){var a=this;this.eventHandler.listen(document.body,"devsite-before-page-change",function(){return void wT(a)});this.eventHandler.listen(document.body,"devsite-award-granted",function(b){(b=b.ma)&&b.detail&&xT(a,b.detail.award)});this.eventHandler.listen(document.body,["devsite-page-loaded","devsite-page-changed"],function(){a.Jd();yT(a)})};try{window.customElements.define("devsite-badger",vT)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBadger",a)};})(_ds_www);
