; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\Documents and Settings\Michael\Desktop\bte_lighter\Demos\Demo11\SysCore\Kernel\entry.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?kernel_entry@@YAXPAUmultiboot_info@@@Z		; kernel_entry
EXTRN	?Exit@@YAXXZ:PROC				; Exit
EXTRN	?kmain@@YAHPAUmultiboot_info@@@Z:PROC		; kmain
EXTRN	?InitializeConstructors@@YAXXZ:PROC		; InitializeConstructors
; Function compile flags: /Ogspy
; File c:\documents and settings\michael\desktop\bte_lighter\demos\demo11\syscore\kernel\entry.cpp
;	COMDAT ?kernel_entry@@YAXPAUmultiboot_info@@@Z
_TEXT	SEGMENT
_bootinfo$ = 8						; size = 4
?kernel_entry@@YAXPAUmultiboot_info@@@Z PROC		; kernel_entry, COMDAT

; 19   : 
; 20   : #ifdef ARCH_X86
; 21   : 
; 22   : 	// Set registers for protected mode
; 23   : 	_asm {
; 24   : 		cli

	cli

; 25   : 		mov ax, 10h

	mov	ax, 16					; 00000010H

; 26   : 		mov ds, ax

	mov	ds, ax

; 27   : 		mov es, ax

	mov	es, ax

; 28   : 		mov fs, ax

	mov	fs, ax

; 29   : 		mov gs, ax

	mov	gs, ax

; 30   : 	}
; 31   : #endif //ARCH_X86
; 32   : 
; 33   : 	InitializeConstructors();

	call	?InitializeConstructors@@YAXXZ		; InitializeConstructors

; 34   : 	kmain (bootinfo);

	push	DWORD PTR _bootinfo$[esp-4]
	call	?kmain@@YAHPAUmultiboot_info@@@Z	; kmain
	pop	ecx

; 35   : 	Exit ();

	call	?Exit@@YAXXZ				; Exit

; 39   : 		cli

	cli

; 40   : 		hlt

	hlt

; 36   : 
; 37   : #ifdef ARCH_X86
; 38   : 	_asm {

$LL2@kernel_ent:

; 41   : 	}
; 42   : #endif
; 43   : 
; 44   : 	for (;;);

	jmp	SHORT $LL2@kernel_ent
?kernel_entry@@YAXPAUmultiboot_info@@@Z ENDP		; kernel_entry
_TEXT	ENDS
END
