; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\Documents and Settings\Michael\Desktop\bte_lighter\Demos_Old\Demo5\SysCore\Kernel\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Ogtpy
; File c:\documents and settings\michael\desktop\bte_lighter\demos_old\demo5\syscore\kernel\main.cpp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 9    : 
; 10   : 
; 11   : }

	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
END
